#!/usr/bin/env bun
/**
 * Build-time SCREENPLAY → typed model codegen.
 *
 * Reads the 4 real per-demo SCREENPLAY.md files and runs the PURE parser in
 * demo/dashboard/screenplay.ts (`parseBeatsRaw` — the raw-text model, so the
 * React app does escaping + inline-markdown in JSX, not HTML strings). Emits
 * src/model.gen.ts. The browser never sees .md or the parser — only the data.
 *
 * Invoked by the Vite plugin (buildStart, dev + build) and runnable standalone:
 *   bun run scripts/gen-model.ts
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { findResetCmd, parseBeatsRaw, parseGapWow, type RawBeat } from '../../screenplay.ts'

const HERE = dirname(fileURLToPath(import.meta.url)) // demo/dashboard/app/scripts
const APP = join(HERE, '..') // demo/dashboard/app
const DEMO_ROOT = join(APP, '..', '..') // demo/

// Same demo registry as build.ts (tab labels + explainer siblings).
const DEMO_DEFS: { id: string; dir: string; tab: string; explainer: string | null }[] = [
  { id: 'md', dir: 'md', tab: 'notion md', explainer: 'notion-md.html' },
  { id: 'sqlite', dir: 'sqlite', tab: 'notion sqlite', explainer: 'notion-sqlite.html' },
  { id: 'schema', dir: 'schema', tab: 'notion schema', explainer: 'notion-schema.html' },
  { id: 'react', dir: 'react', tab: 'notion-react', explainer: 'notion-react.html' },
]

interface DemoModel {
  id: string
  tab: string
  gapwow: string
  resetCmd: string | null
  explainerSrc: string | null
  beats: RawBeat[]
}

export const buildModel = (): DemoModel[] =>
  DEMO_DEFS.map((def) => {
    const md = readFileSync(join(DEMO_ROOT, def.dir, 'SCREENPLAY.md'), 'utf8')
    return {
      id: def.id,
      tab: def.tab,
      gapwow: parseGapWow(md),
      resetCmd: findResetCmd(md),
      // explainerSrc stays a plain RELATIVE sibling ref (served next to control.next.html);
      // Vite must never try to bundle it.
      explainerSrc: def.explainer,
      beats: parseBeatsRaw(md),
    }
  })

export const genModel = (): void => {
  const demos = buildModel()
  const out = `// GENERATED by scripts/gen-model.ts — do not edit. Source: demo/{md,sqlite,schema,react}/SCREENPLAY.md
import type { RawBeat } from '../../screenplay.ts'

export interface DemoModel {
  id: string
  tab: string
  gapwow: string
  resetCmd: string | null
  explainerSrc: string | null
  beats: RawBeat[]
}

export const DEMOS: DemoModel[] = ${JSON.stringify(demos, null, 2)}
`
  writeFileSync(join(APP, 'src', 'model.gen.ts'), out)
}

// Run when invoked directly (bun run scripts/gen-model.ts)
if (import.meta.main) {
  genModel()
  const demos = buildModel()
  console.log(`gen-model: ${demos.map((d) => `${d.id}(${d.beats.length} beats)`).join(', ')}`)
}
