packages:
  - 'packages/**'
  # Note: packages/@overeng/react-inspector is a git submodule with its own tooling (tsup, ESLint)
  # We include it in the workspace but keep its build system separate

catalog:
  # Effect ecosystem
  effect: 3.19.13
  "@effect/platform": 0.94.0
  "@effect/platform-node": 0.104.0
  "@effect/cli": 0.73.0
  "@effect/vitest": 0.27.0
  "@effect/printer": 0.47.0
  "@effect/printer-ansi": 0.47.0
  "@effect/typeclass": 0.38.0

  # React ecosystem
  react: 19.2.3
  react-dom: 19.2.3
  react-aria-components: 1.14.0

  # Type definitions
  "@types/react": 19.2.3
  "@types/react-dom": 19.0.3

  # Build tools
  typescript: 5.8.3
  vite: 6.3.5
  vitest: 3.2.4
  "@vitejs/plugin-react": 4.5.2

  # Styling
  tailwindcss: 4.1.10
  "@tailwindcss/vite": 4.1.10

  # Storybook
  storybook: 10.1.11
  "@storybook/react": 10.1.11
  "@storybook/react-vite": 10.1.11
