import { describe, expect, it } from 'vitest'

import {
  generateSchemaCode,
  getAvailableTransforms,
  getDefaultTransform,
  isReadOnlyProperty,
  PROPERTY_TRANSFORMS,
} from './codegen.ts'
import type { DatabaseInfo, NotionPropertyType, PropertyInfo } from './introspect.ts'

describe('codegen', () => {
  describe('generateSchemaCode', () => {
    it('should generate basic schema for a simple database', () => {
      const dbInfo: DatabaseInfo = {
        id: 'test-db-id',
        name: 'Test Database',
        url: 'https://notion.so/test-db',
        properties: [
          { id: 'title-prop', name: 'Name', type: 'title' },
          { id: 'text-prop', name: 'Description', type: 'rich_text' },
          { id: 'num-prop', name: 'Count', type: 'number' },
          { id: 'check-prop', name: 'Done', type: 'checkbox' },
        ],
      }

      const code = generateSchemaCode(dbInfo, 'TestDatabase')

      expect(code).toMatchInlineSnapshot(`
        "// Generated by notion-effect-schema-gen
        // Database: Test Database
        // ID: test-db-id
        // URL: https://notion.so/test-db

        import { Schema } from 'effect'
        import {
          Checkbox,
          Num,
          RichTextProp,
          Title,
        } from '@overeng/notion-effect-schema'

        // -----------------------------------------------------------------------------
        // Read Schema
        // -----------------------------------------------------------------------------

        /**
         * Schema for reading pages from the "Test Database" database.
         */
        export const TestDatabasePageProperties = Schema.Struct({
          Name: Title.asString,
          Description: RichTextProp.asString,
          Count: Num.asNumber,
          Done: Checkbox.asBoolean,
        }).annotations({
          identifier: 'TestDatabasePageProperties',
          description: 'Read schema for Test Database database pages',
        })

        export type TestDatabasePageProperties = typeof TestDatabasePageProperties.Type

        /**
         * Decode properties from unknown data (throws on failure).
         */
        export const decodeTestDatabaseProperties = Schema.decodeUnknownSync(TestDatabasePageProperties)

        /**
         * Decode properties from unknown data (returns Effect).
         */
        export const decodeTestDatabasePropertiesEffect = Schema.decodeUnknown(TestDatabasePageProperties)
        "
      `)
    })

    it('should include generator version when provided', () => {
      const dbInfo: DatabaseInfo = {
        id: 'test-db-id',
        name: 'Test Database',
        url: 'https://notion.so/test-db',
        properties: [{ id: 'title-prop', name: 'Name', type: 'title' }],
      }

      const code = generateSchemaCode(dbInfo, 'TestDatabase', {
        generatorVersion: '0.1.0',
      })

      expect(code).toMatchInlineSnapshot(`
        "// Generated by notion-effect-schema-gen v0.1.0
        // Database: Test Database
        // ID: test-db-id
        // URL: https://notion.so/test-db

        import { Schema } from 'effect'
        import {
          Title,
        } from '@overeng/notion-effect-schema'

        // -----------------------------------------------------------------------------
        // Read Schema
        // -----------------------------------------------------------------------------

        /**
         * Schema for reading pages from the "Test Database" database.
         */
        export const TestDatabasePageProperties = Schema.Struct({
          Name: Title.asString,
        }).annotations({
          identifier: 'TestDatabasePageProperties',
          description: 'Read schema for Test Database database pages',
        })

        export type TestDatabasePageProperties = typeof TestDatabasePageProperties.Type

        /**
         * Decode properties from unknown data (throws on failure).
         */
        export const decodeTestDatabaseProperties = Schema.decodeUnknownSync(TestDatabasePageProperties)

        /**
         * Decode properties from unknown data (returns Effect).
         */
        export const decodeTestDatabasePropertiesEffect = Schema.decodeUnknown(TestDatabasePageProperties)
        "
      `)
    })

    it('should handle property names with special characters', () => {
      const dbInfo: DatabaseInfo = {
        id: 'test-db-id',
        name: 'Test',
        url: 'https://notion.so/test',
        properties: [
          { id: 'prop1', name: 'Due Date', type: 'date' },
          { id: 'prop2', name: 'Project Name', type: 'title' },
          { id: 'prop3', name: "User's Choice", type: 'select' },
        ],
      }

      const code = generateSchemaCode(dbInfo, 'Test')

      expect(code).toMatchInlineSnapshot(`
        "// Generated by notion-effect-schema-gen
        // Database: Test
        // ID: test-db-id
        // URL: https://notion.so/test

        import { Schema } from 'effect'
        import {
          DateProp,
          Select,
          Title,
        } from '@overeng/notion-effect-schema'

        // -----------------------------------------------------------------------------
        // Read Schema
        // -----------------------------------------------------------------------------

        /**
         * Schema for reading pages from the "Test" database.
         */
        export const TestPageProperties = Schema.Struct({
          'Due Date': DateProp.asOption,
          'Project Name': Title.asString,
          'User\\'s Choice': Select.asOption,
        }).annotations({
          identifier: 'TestPageProperties',
          description: 'Read schema for Test database pages',
        })

        export type TestPageProperties = typeof TestPageProperties.Type

        /**
         * Decode properties from unknown data (throws on failure).
         */
        export const decodeTestProperties = Schema.decodeUnknownSync(TestPageProperties)

        /**
         * Decode properties from unknown data (returns Effect).
         */
        export const decodeTestPropertiesEffect = Schema.decodeUnknown(TestPageProperties)
        "
      `)
    })

    it('should respect custom transform configuration', () => {
      const dbInfo: DatabaseInfo = {
        id: 'test-db-id',
        name: 'Test',
        url: 'https://notion.so/test',
        properties: [
          { id: 'prop1', name: 'Status', type: 'select' },
          { id: 'prop2', name: 'Tags', type: 'multi_select' },
          { id: 'prop3', name: 'Website', type: 'url' },
        ],
      }

      const code = generateSchemaCode(dbInfo, 'Test', {
        transforms: { Status: 'raw', Tags: 'raw', Website: 'asString' },
      })

      expect(code).toMatchInlineSnapshot(`
        "// Generated by notion-effect-schema-gen
        // Database: Test
        // ID: test-db-id
        // URL: https://notion.so/test
        // @config { transforms: { Status: raw, Tags: raw, Website: asString } }

        import { Schema } from 'effect'
        import {
          MultiSelect,
          Select,
          Url,
        } from '@overeng/notion-effect-schema'

        // -----------------------------------------------------------------------------
        // Read Schema
        // -----------------------------------------------------------------------------

        /**
         * Schema for reading pages from the "Test" database.
         */
        export const TestPageProperties = Schema.Struct({
          Status: Select.raw,
          Tags: MultiSelect.raw,
          Website: Url.asString,
        }).annotations({
          identifier: 'TestPageProperties',
          description: 'Read schema for Test database pages',
        })

        export type TestPageProperties = typeof TestPageProperties.Type

        /**
         * Decode properties from unknown data (throws on failure).
         */
        export const decodeTestProperties = Schema.decodeUnknownSync(TestPageProperties)

        /**
         * Decode properties from unknown data (returns Effect).
         */
        export const decodeTestPropertiesEffect = Schema.decodeUnknown(TestPageProperties)
        "
      `)
    })

    it('should fall back to default transform for invalid config', () => {
      const dbInfo: DatabaseInfo = {
        id: 'test-db-id',
        name: 'Test',
        url: 'https://notion.so/test',
        properties: [{ id: 'prop1', name: 'Status', type: 'select' }],
      }

      const code = generateSchemaCode(dbInfo, 'Test', {
        transforms: { Status: 'invalidTransform' },
      })

      expect(code).toContain('Status: Select.asOption')
    })

    it('should convert name to PascalCase', () => {
      const dbInfo: DatabaseInfo = {
        id: 'test-db-id',
        name: 'Test',
        url: 'https://notion.so/test',
        properties: [{ id: 'prop1', name: 'Title', type: 'title' }],
      }

      const code = generateSchemaCode(dbInfo, 'my-test-database')

      expect(code).toContain('export const MyTestDatabasePageProperties')
      expect(code).toContain('export type MyTestDatabasePageProperties')
    })

    it('should include property descriptions as comments', () => {
      const dbInfo: DatabaseInfo = {
        id: 'test-db-id',
        name: 'Test',
        url: 'https://notion.so/test',
        properties: [
          {
            id: 'prop1',
            name: 'Status',
            type: 'select',
            description: 'Current task status',
          },
        ],
      }

      const code = generateSchemaCode(dbInfo, 'Test')

      expect(code).toMatchInlineSnapshot(`
        "// Generated by notion-effect-schema-gen
        // Database: Test
        // ID: test-db-id
        // URL: https://notion.so/test

        import { Schema } from 'effect'
        import {
          Select,
        } from '@overeng/notion-effect-schema'

        // -----------------------------------------------------------------------------
        // Read Schema
        // -----------------------------------------------------------------------------

        /**
         * Schema for reading pages from the "Test" database.
         */
        export const TestPageProperties = Schema.Struct({
          /** Current task status */
          Status: Select.asOption,
        }).annotations({
          identifier: 'TestPageProperties',
          description: 'Read schema for Test database pages',
        })

        export type TestPageProperties = typeof TestPageProperties.Type

        /**
         * Decode properties from unknown data (throws on failure).
         */
        export const decodeTestProperties = Schema.decodeUnknownSync(TestPageProperties)

        /**
         * Decode properties from unknown data (returns Effect).
         */
        export const decodeTestPropertiesEffect = Schema.decodeUnknown(TestPageProperties)
        "
      `)
    })

    it('should handle all property types with default transforms', () => {
      const propertyTypes: Array<{ type: PropertyInfo['type']; expected: string }> = [
        { type: 'title', expected: 'Title.asString' },
        { type: 'rich_text', expected: 'RichTextProp.asString' },
        { type: 'number', expected: 'Num.asNumber' },
        { type: 'select', expected: 'Select.asOption' },
        { type: 'multi_select', expected: 'MultiSelect.asStrings' },
        { type: 'status', expected: 'Status.asOption' },
        { type: 'date', expected: 'DateProp.asOption' },
        { type: 'people', expected: 'People.asIds' },
        { type: 'files', expected: 'Files.asUrls' },
        { type: 'checkbox', expected: 'Checkbox.asBoolean' },
        { type: 'url', expected: 'Url.asOption' },
        { type: 'email', expected: 'Email.asOption' },
        { type: 'phone_number', expected: 'PhoneNumber.asOption' },
        { type: 'formula', expected: 'Formula.raw' },
        { type: 'relation', expected: 'Relation.asIds' },
        { type: 'created_time', expected: 'CreatedTime.asDate' },
        { type: 'created_by', expected: 'CreatedBy.raw' },
        { type: 'last_edited_time', expected: 'LastEditedTime.asDate' },
        { type: 'last_edited_by', expected: 'LastEditedBy.raw' },
        { type: 'unique_id', expected: 'UniqueId.raw' },
      ]

      for (const { type, expected } of propertyTypes) {
        const dbInfo: DatabaseInfo = {
          id: 'test',
          name: 'Test',
          url: 'https://notion.so/test',
          properties: [{ id: 'prop', name: 'Prop', type }],
        }

        const code = generateSchemaCode(dbInfo, 'Test')
        expect(code).toContain(`Prop: ${expected}`)
      }
    })

    it('should handle unknown property types gracefully', () => {
      const dbInfo: DatabaseInfo = {
        id: 'test-db-id',
        name: 'Test',
        url: 'https://notion.so/test',
        properties: [{ id: 'prop1', name: 'Unknown', type: 'button' as PropertyInfo['type'] }],
      }

      const code = generateSchemaCode(dbInfo, 'Test')

      expect(code).toContain('Unknown: Schema.Unknown')
    })
  })

  describe('getAvailableTransforms', () => {
    it('should return available transforms for each type', () => {
      expect(getAvailableTransforms('title')).toContain('raw')
      expect(getAvailableTransforms('title')).toContain('asString')

      expect(getAvailableTransforms('select')).toContain('raw')
      expect(getAvailableTransforms('select')).toContain('asOption')
      expect(getAvailableTransforms('select')).toContain('asString')

      expect(getAvailableTransforms('checkbox')).toContain('raw')
      expect(getAvailableTransforms('checkbox')).toContain('asBoolean')
    })

    it('should return raw for unknown types', () => {
      expect(getAvailableTransforms('unknown')).toEqual(['raw'])
    })
  })

  describe('getDefaultTransform', () => {
    it('should return correct defaults', () => {
      expect(getDefaultTransform('title')).toBe('asString')
      expect(getDefaultTransform('number')).toBe('asNumber')
      expect(getDefaultTransform('checkbox')).toBe('asBoolean')
      expect(getDefaultTransform('select')).toBe('asOption')
      expect(getDefaultTransform('formula')).toBe('raw')
    })

    it('should return raw for unknown types', () => {
      expect(getDefaultTransform('unknown')).toBe('raw')
    })
  })

  describe('PROPERTY_TRANSFORMS', () => {
    it('should have transforms defined for all common property types', () => {
      const expectedTypes = [
        'title',
        'rich_text',
        'number',
        'select',
        'multi_select',
        'status',
        'date',
        'people',
        'files',
        'checkbox',
        'url',
        'email',
        'phone_number',
        'formula',
        'relation',
        'rollup',
        'created_time',
        'created_by',
        'last_edited_time',
        'last_edited_by',
        'unique_id',
        'verification',
        'button',
      ] as const satisfies readonly NotionPropertyType[]

      for (const type of expectedTypes) {
        expect(PROPERTY_TRANSFORMS[type]).toBeDefined()
        expect(PROPERTY_TRANSFORMS[type]).toContain('raw')
      }
    })
  })

  describe('isReadOnlyProperty', () => {
    it('should return true for read-only properties', () => {
      expect(isReadOnlyProperty('formula')).toBe(true)
      expect(isReadOnlyProperty('rollup')).toBe(true)
      expect(isReadOnlyProperty('created_time')).toBe(true)
      expect(isReadOnlyProperty('created_by')).toBe(true)
      expect(isReadOnlyProperty('last_edited_time')).toBe(true)
      expect(isReadOnlyProperty('last_edited_by')).toBe(true)
      expect(isReadOnlyProperty('unique_id')).toBe(true)
    })

    it('should return false for writable properties', () => {
      expect(isReadOnlyProperty('title')).toBe(false)
      expect(isReadOnlyProperty('rich_text')).toBe(false)
      expect(isReadOnlyProperty('number')).toBe(false)
      expect(isReadOnlyProperty('select')).toBe(false)
      expect(isReadOnlyProperty('checkbox')).toBe(false)
    })
  })

  describe('generateSchemaCode with options', () => {
    it('should generate Write schema when includeWrite is true', () => {
      const dbInfo: DatabaseInfo = {
        id: 'test-db-id',
        name: 'Test',
        url: 'https://notion.so/test',
        properties: [
          { id: 'prop1', name: 'Name', type: 'title' },
          { id: 'prop2', name: 'Status', type: 'select' },
          { id: 'prop3', name: 'CreatedAt', type: 'created_time' },
        ],
      }

      const code = generateSchemaCode(dbInfo, 'Test', { includeWrite: true })

      expect(code).toMatchInlineSnapshot(`
        "// Generated by notion-effect-schema-gen
        // Database: Test
        // ID: test-db-id
        // URL: https://notion.so/test
        // @config { includeWrite: true }

        import { Schema } from 'effect'
        import {
          CreatedTime,
          Select,
          Title,
        } from '@overeng/notion-effect-schema'

        // -----------------------------------------------------------------------------
        // Read Schema
        // -----------------------------------------------------------------------------

        /**
         * Schema for reading pages from the "Test" database.
         */
        export const TestPageProperties = Schema.Struct({
          Name: Title.asString,
          Status: Select.asOption,
          CreatedAt: CreatedTime.asDate,
        }).annotations({
          identifier: 'TestPageProperties',
          description: 'Read schema for Test database pages',
        })

        export type TestPageProperties = typeof TestPageProperties.Type

        /**
         * Decode properties from unknown data (throws on failure).
         */
        export const decodeTestProperties = Schema.decodeUnknownSync(TestPageProperties)

        /**
         * Decode properties from unknown data (returns Effect).
         */
        export const decodeTestPropertiesEffect = Schema.decodeUnknown(TestPageProperties)

        // -----------------------------------------------------------------------------
        // Write Schema
        // -----------------------------------------------------------------------------

        /**
         * Schema for creating/updating pages in the "Test" database.
         * Note: Read-only properties (formula, rollup, created_time, etc.) are excluded.
         */
        export const TestPageWrite = Schema.Struct({
          Name: Title.Write.fromString,
          Status: Select.Write.fromName,
        }).annotations({
          identifier: 'TestPageWrite',
          description: 'Write schema for Test database pages',
        })

        export type TestPageWrite = typeof TestPageWrite.Type

        /**
         * Decode write data from simple types (throws on failure).
         */
        export const decodeTestWrite = Schema.decodeUnknownSync(TestPageWrite)

        /**
         * Decode write data from simple types (returns Effect).
         */
        export const decodeTestWriteEffect = Schema.decodeUnknown(TestPageWrite)

        /**
         * Encode write data back to simple types (throws on failure).
         */
        export const encodeTestWrite = Schema.encodeSync(TestPageWrite)

        /**
         * Encode write data back to simple types (returns Effect).
         */
        export const encodeTestWriteEffect = Schema.encode(TestPageWrite)
        "
      `)
    })

    it('should generate typed options when typedOptions is true', () => {
      const dbInfo: DatabaseInfo = {
        id: 'test-db-id',
        name: 'Test',
        url: 'https://notion.so/test',
        properties: [
          {
            id: 'prop1',
            name: 'Status',
            type: 'select',
            select: {
              options: [
                { id: '1', name: 'Not Started', color: 'gray' },
                { id: '2', name: 'In Progress', color: 'blue' },
                { id: '3', name: 'Done', color: 'green' },
              ],
            },
          },
          {
            id: 'prop2',
            name: 'Priority',
            type: 'multi_select',
            multi_select: {
              options: [
                { id: '1', name: 'High', color: 'red' },
                { id: '2', name: 'Low', color: 'gray' },
              ],
            },
          },
        ],
      }

      const code = generateSchemaCode(dbInfo, 'Test', { typedOptions: true })

      expect(code).toMatchInlineSnapshot(`
        "// Generated by notion-effect-schema-gen
        // Database: Test
        // ID: test-db-id
        // URL: https://notion.so/test
        // @config { typedOptions: true }

        import { Schema } from 'effect'
        import {
          MultiSelect,
          Select,
        } from '@overeng/notion-effect-schema'

        // -----------------------------------------------------------------------------
        // Typed Options
        // -----------------------------------------------------------------------------

        /** Options for "Status" property */
        export const TestStatusOption = Schema.Literal('Done', 'In Progress', 'Not Started').annotations({
          identifier: 'TestStatusOption'
        })
        export type TestStatusOption = typeof TestStatusOption.Type

        /** Options for "Priority" property */
        export const TestPriorityOption = Schema.Literal('High', 'Low').annotations({
          identifier: 'TestPriorityOption'
        })
        export type TestPriorityOption = typeof TestPriorityOption.Type


        // -----------------------------------------------------------------------------
        // Read Schema
        // -----------------------------------------------------------------------------

        /**
         * Schema for reading pages from the "Test" database.
         */
        export const TestPageProperties = Schema.Struct({
          Status: Select.asOption,
          Priority: MultiSelect.asStrings,
        }).annotations({
          identifier: 'TestPageProperties',
          description: 'Read schema for Test database pages',
        })

        export type TestPageProperties = typeof TestPageProperties.Type

        /**
         * Decode properties from unknown data (throws on failure).
         */
        export const decodeTestProperties = Schema.decodeUnknownSync(TestPageProperties)

        /**
         * Decode properties from unknown data (returns Effect).
         */
        export const decodeTestPropertiesEffect = Schema.decodeUnknown(TestPageProperties)
        "
      `)
    })

    it('should preserve PascalCase in names', () => {
      const dbInfo: DatabaseInfo = {
        id: 'test',
        name: 'Test',
        url: 'https://notion.so/test',
        properties: [{ id: 'prop', name: 'Title', type: 'title' }],
      }

      expect(generateSchemaCode(dbInfo, 'MyDatabase')).toContain('MyDatabasePageProperties')
      expect(generateSchemaCode(dbInfo, 'TestDB')).toContain('TestDBPageProperties')
      expect(generateSchemaCode(dbInfo, 'my-test-db')).toContain('MyTestDbPageProperties')
    })

    it('should not include @config comment when no options are set', () => {
      const dbInfo: DatabaseInfo = {
        id: 'test-db-id',
        name: 'Test',
        url: 'https://notion.so/test',
        properties: [{ id: 'prop1', name: 'Name', type: 'title' }],
      }

      const code = generateSchemaCode(dbInfo, 'Test')

      expect(code).not.toContain('@config')
    })

    it('should include @config comment with all options', () => {
      const dbInfo: DatabaseInfo = {
        id: 'test-db-id',
        name: 'Test',
        url: 'https://notion.so/test',
        properties: [{ id: 'prop1', name: 'Name', type: 'title' }],
      }

      const code = generateSchemaCode(dbInfo, 'Test', {
        includeWrite: true,
        typedOptions: true,
        includeApi: true,
        transforms: { Status: 'asOption', Priority: 'asString' },
        schemaNameOverride: 'MyCustomName',
      })

      expect(code).toMatchInlineSnapshot(`
        "// Generated by notion-effect-schema-gen
        // Database: Test
        // ID: test-db-id
        // URL: https://notion.so/test
        // @config { name: MyCustomName, includeWrite: true, typedOptions: true, includeApi: true, transforms: { Status: asOption, Priority: asString } }

        import { Schema } from 'effect'
        import {
          Title,
        } from '@overeng/notion-effect-schema'

        // -----------------------------------------------------------------------------
        // Read Schema
        // -----------------------------------------------------------------------------

        /**
         * Schema for reading pages from the "Test" database.
         */
        export const TestPageProperties = Schema.Struct({
          Name: Title.asString,
        }).annotations({
          identifier: 'TestPageProperties',
          description: 'Read schema for Test database pages',
        })

        export type TestPageProperties = typeof TestPageProperties.Type

        /**
         * Decode properties from unknown data (throws on failure).
         */
        export const decodeTestProperties = Schema.decodeUnknownSync(TestPageProperties)

        /**
         * Decode properties from unknown data (returns Effect).
         */
        export const decodeTestPropertiesEffect = Schema.decodeUnknown(TestPageProperties)

        // -----------------------------------------------------------------------------
        // Write Schema
        // -----------------------------------------------------------------------------

        /**
         * Schema for creating/updating pages in the "Test" database.
         * Note: Read-only properties (formula, rollup, created_time, etc.) are excluded.
         */
        export const TestPageWrite = Schema.Struct({
          Name: Title.Write.fromString,
        }).annotations({
          identifier: 'TestPageWrite',
          description: 'Write schema for Test database pages',
        })

        export type TestPageWrite = typeof TestPageWrite.Type

        /**
         * Decode write data from simple types (throws on failure).
         */
        export const decodeTestWrite = Schema.decodeUnknownSync(TestPageWrite)

        /**
         * Decode write data from simple types (returns Effect).
         */
        export const decodeTestWriteEffect = Schema.decodeUnknown(TestPageWrite)

        /**
         * Encode write data back to simple types (throws on failure).
         */
        export const encodeTestWrite = Schema.encodeSync(TestPageWrite)

        /**
         * Encode write data back to simple types (returns Effect).
         */
        export const encodeTestWriteEffect = Schema.encode(TestPageWrite)
        "
      `)
    })

    it('should quote special characters in transform keys', () => {
      const dbInfo: DatabaseInfo = {
        id: 'test-db-id',
        name: 'Test',
        url: 'https://notion.so/test',
        properties: [{ id: 'prop1', name: 'Name', type: 'title' }],
      }

      const code = generateSchemaCode(dbInfo, 'Test', {
        transforms: { 'Due Date': 'asOption', 'My Status': 'raw' },
      })

      expect(code).toContain(
        '// @config { transforms: { "Due Date": asOption, "My Status": raw } }',
      )
    })
  })
})
