import { describe, expect, it } from 'vitest'

import { computeDiff, formatDiff, hasDifferences, parseGeneratedFile } from './diff.ts'
import type { DatabaseInfo } from './introspect.ts'

describe('diff', () => {
  describe('parseGeneratedFile', () => {
    it('should parse database ID and name from header', () => {
      const content = `// Generated by notion-effect-schema-gen v0.1.0
// Database: Test Database
// ID: abc123-def456
// URL: https://notion.so/test

import { Schema } from 'effect'
`
      const result = parseGeneratedFile(content)

      expect(result.databaseId).toBe('abc123-def456')
      expect(result.databaseName).toBe('Test Database')
      expect(result.readSchemaFound).toBe(false)
    })

    it('should parse simple property names', () => {
      const content = `// Database: Test
// ID: abc123

export const TestPageProperties = Schema.Struct({
  Name: NotionSchema.title,
  Count: NotionSchema.number,
  Done: NotionSchema.checkbox,
})
`
      const result = parseGeneratedFile(content)

      expect(result.properties).toEqual([
        { name: 'Name', transformKey: 'title' },
        { name: 'Count', transformKey: 'number' },
        { name: 'Done', transformKey: 'checkbox' },
      ])
      expect(result.readSchemaFound).toBe(true)
    })

    it('should parse quoted property names with spaces', () => {
      const content = `// ID: abc123

export const TestPageProperties = Schema.Struct({
  'Due Date': NotionSchema.dateOption,
  'Project Name': NotionSchema.title,
})
`
      const result = parseGeneratedFile(content)

      expect(result.properties).toEqual([
        { name: 'Due Date', transformKey: 'dateOption' },
        { name: 'Project Name', transformKey: 'title' },
      ])
      expect(result.readSchemaFound).toBe(true)
    })

    it('should handle properties with comments', () => {
      const content = `// ID: abc123

export const TestPageProperties = Schema.Struct({
  Status: NotionSchema.selectOption, // Current status
  Priority: NotionSchema.selectRaw,
})
`
      const result = parseGeneratedFile(content)

      expect(result.properties).toEqual([
        { name: 'Status', transformKey: 'selectOption' },
        { name: 'Priority', transformKey: 'selectRaw' },
      ])
      expect(result.readSchemaFound).toBe(true)
    })

    it('should handle empty file', () => {
      const result = parseGeneratedFile('')

      expect(result.databaseId).toBeUndefined()
      expect(result.databaseName).toBeUndefined()
      expect(result.properties).toEqual([])
      expect(result.readSchemaFound).toBe(false)
    })

    it('should handle file without schema struct', () => {
      const content = `// ID: abc123
// Some other content
const foo = 'bar'
`
      const result = parseGeneratedFile(content)

      expect(result.databaseId).toBe('abc123')
      expect(result.properties).toEqual([])
      expect(result.readSchemaFound).toBe(false)
    })
  })

  describe('computeDiff', () => {
    it('should detect added properties', () => {
      const live: DatabaseInfo = {
        id: 'abc123',
        name: 'Test',
        url: 'https://notion.so/test',
        properties: [
          { id: 'p1', name: 'Name', type: 'title' },
          { id: 'p2', name: 'NewField', type: 'rich_text' },
        ],
      }

      const generated = {
        databaseId: 'abc123',
        databaseName: 'Test',
        readSchemaFound: true,
        properties: [{ name: 'Name', transformKey: 'title' }],
      }

      const result = computeDiff({ live, generated })

      expect(result.databaseIdMatch).toBe(true)
      expect(result.properties).toHaveLength(1)
      expect(result.properties[0]).toEqual({
        name: 'NewField',
        type: 'added',
        live: { type: 'rich_text', transform: 'asString' },
      })
    })

    it('should detect removed properties', () => {
      const live: DatabaseInfo = {
        id: 'abc123',
        name: 'Test',
        url: 'https://notion.so/test',
        properties: [{ id: 'p1', name: 'Name', type: 'title' }],
      }

      const generated = {
        databaseId: 'abc123',
        databaseName: 'Test',
        readSchemaFound: true,
        properties: [
          { name: 'Name', transformKey: 'title' },
          { name: 'OldField', transformKey: 'richTextString' },
        ],
      }

      const result = computeDiff({ live, generated })

      expect(result.properties).toHaveLength(1)
      expect(result.properties[0]).toEqual({
        name: 'OldField',
        type: 'removed',
        generated: { transformKey: 'richTextString' },
      })
    })

    it('should detect type changes', () => {
      const live: DatabaseInfo = {
        id: 'abc123',
        name: 'Test',
        url: 'https://notion.so/test',
        properties: [{ id: 'p1', name: 'Status', type: 'status' }],
      }

      const generated = {
        databaseId: 'abc123',
        databaseName: 'Test',
        readSchemaFound: true,
        properties: [{ name: 'Status', transformKey: 'selectOption' }],
      }

      const result = computeDiff({ live, generated })

      expect(result.properties).toHaveLength(1)
      expect(result.properties[0]).toEqual({
        name: 'Status',
        type: 'type_changed',
        live: { type: 'status', transform: 'asOption' },
        generated: { transformKey: 'selectOption' },
      })
    })

    it('should detect database ID mismatch', () => {
      const live: DatabaseInfo = {
        id: 'abc123',
        name: 'Test',
        url: 'https://notion.so/test',
        properties: [],
      }

      const generated = {
        databaseId: 'different-id',
        databaseName: 'Test',
        readSchemaFound: true,
        properties: [],
      }

      const result = computeDiff({ live, generated })

      expect(result.databaseIdMatch).toBe(false)
    })

    it('should handle no differences', () => {
      const live: DatabaseInfo = {
        id: 'abc123',
        name: 'Test',
        url: 'https://notion.so/test',
        properties: [
          { id: 'p1', name: 'Name', type: 'title' },
          { id: 'p2', name: 'Count', type: 'number' },
        ],
      }

      const generated = {
        databaseId: 'abc123',
        databaseName: 'Test',
        readSchemaFound: true,
        properties: [
          { name: 'Name', transformKey: 'title' },
          { name: 'Count', transformKey: 'number' },
        ],
      }

      const result = computeDiff({ live, generated })

      expect(result.databaseIdMatch).toBe(true)
      expect(result.properties).toHaveLength(0)
      expect(result.options).toHaveLength(0)
    })
  })

  describe('formatDiff', () => {
    it('should format no differences message', () => {
      const diff = {
        databaseIdMatch: true,
        properties: [],
        options: [],
      }

      const lines = formatDiff({ diff, databaseId: 'abc123', filePath: './schema.ts' })

      expect(lines).toContain('No differences found')
    })

    it('should format added properties', () => {
      const diff = {
        databaseIdMatch: true,
        properties: [
          {
            name: 'NewField',
            type: 'added' as const,
            live: { type: 'rich_text' as const, transform: 'asString' },
          },
        ],
        options: [],
      }

      const lines = formatDiff({ diff, databaseId: 'abc123', filePath: './schema.ts' })

      expect(lines.some((l) => l.includes('+ NewField'))).toBe(true)
      expect(lines.some((l) => l.includes('new property in Notion'))).toBe(true)
    })

    it('should format removed properties', () => {
      const diff = {
        databaseIdMatch: true,
        properties: [
          {
            name: 'OldField',
            type: 'removed' as const,
            generated: { transformKey: 'richTextString' },
          },
        ],
        options: [],
      }

      const lines = formatDiff({ diff, databaseId: 'abc123', filePath: './schema.ts' })

      expect(lines.some((l) => l.includes('- OldField'))).toBe(true)
      expect(lines.some((l) => l.includes('removed from Notion'))).toBe(true)
    })

    it('should format type changes', () => {
      const diff = {
        databaseIdMatch: true,
        properties: [
          {
            name: 'Status',
            type: 'type_changed' as const,
            live: { type: 'status' as const, transform: 'asOption' },
            generated: { transformKey: 'selectOption' },
          },
        ],
        options: [],
      }

      const lines = formatDiff({ diff, databaseId: 'abc123', filePath: './schema.ts' })

      expect(lines.some((l) => l.includes('~ Status'))).toBe(true)
      expect(lines.some((l) => l.includes('type changed'))).toBe(true)
    })

    it('should include summary', () => {
      const diff = {
        databaseIdMatch: true,
        properties: [
          {
            name: 'NewField',
            type: 'added' as const,
            live: { type: 'title' as const, transform: 'asString' },
          },
          {
            name: 'OldField',
            type: 'removed' as const,
            generated: { transformKey: 'title' },
          },
        ],
        options: [],
      }

      const lines = formatDiff({ diff, databaseId: 'abc123', filePath: './schema.ts' })

      expect(lines.some((l) => l.includes('Summary:'))).toBe(true)
      expect(lines.some((l) => l.includes('1 added'))).toBe(true)
      expect(lines.some((l) => l.includes('1 removed'))).toBe(true)
    })

    it('should warn about database ID mismatch', () => {
      const diff = {
        databaseIdMatch: false,
        properties: [],
        options: [],
      }

      const lines = formatDiff({ diff, databaseId: 'abc123', filePath: './schema.ts' })

      expect(lines.some((l) => l.includes('WARNING'))).toBe(true)
      expect(lines.some((l) => l.includes('does not match'))).toBe(true)
      expect(lines.some((l) => l.includes('database ID mismatch'))).toBe(true)
      expect(lines.some((l) => l.includes('Summary:'))).toBe(true)
    })
  })

  describe('hasDifferences', () => {
    it('should return false for no differences', () => {
      expect(
        hasDifferences({
          databaseIdMatch: true,
          properties: [],
          options: [],
        }),
      ).toBe(false)
    })

    it('should return true for database ID mismatch', () => {
      expect(
        hasDifferences({
          databaseIdMatch: false,
          properties: [],
          options: [],
        }),
      ).toBe(true)
    })

    it('should return true for property differences', () => {
      expect(
        hasDifferences({
          databaseIdMatch: true,
          properties: [
            { name: 'Test', type: 'added', live: { type: 'title', transform: 'asString' } },
          ],
          options: [],
        }),
      ).toBe(true)
    })

    it('should return true for options differences', () => {
      expect(
        hasDifferences({
          databaseIdMatch: true,
          properties: [],
          options: [{ name: 'Status', added: ['New'], removed: [] }],
        }),
      ).toBe(true)
    })
  })
})
