/**
 * storybook/no-redundant-story-name oxlint rule.
 *
 * A story should not declare an explicit `name`/`storyName` that is redundant
 * with the name Storybook would derive from the export name. Covers CSF3
 * (object export property) and CSF2 (`Story.storyName = '...'` assignment).
 *
 * @see Upstream SoT: eslint-plugin-storybook rule `no-redundant-story-name` —
 *   https://github.com/storybookjs/storybook/blob/v10.4.6/code/lib/eslint-plugin/src/rules/no-redundant-story-name.ts
 *
 * Reimplemented from eslint-plugin-storybook@10.4.6. The redundancy comparison
 * uses the same `storyNameFromExport` (lodash-startCase-style) transform; see
 * utils.ts.
 *
 * Resync: when bumping the pinned Storybook version or CSF conventions, re-read
 * the upstream rule and reconcile behavior here. No intentional deviations.
 */

// NOTE: Using `any` types because oxlint JS plugin API doesn't have TypeScript definitions yet

import { storyNameFromExport } from './utils.ts'

/** oxlint rule: flag a story `name`/`storyName` that is redundant with its export name */
export const noRedundantStoryNameRule = {
  meta: {
    type: 'suggestion' as const,
    fixable: 'code' as const,
    docs: {
      description: 'A story should not have a redundant name property',
      recommended: false,
    },
    messages: {
      storyNameIsRedundant:
        'Named exports should not use the name annotation if it is redundant to the name that would be generated by the export name',
    },
    schema: [],
  },
  defaultOptions: [],
  create(context: any) {
    return {
      // CSF3: export const Foo = { name: 'Foo' }
      ExportNamedDeclaration(node: any) {
        if (node.declaration === null || node.declaration === undefined) return

        const decl = node.declaration
        if (decl.type !== 'VariableDeclaration') return

        const declaration = decl.declarations[0]
        if (declaration === undefined || declaration === null) return

        const id = declaration.id
        const init = declaration.init
        if (id?.type !== 'Identifier' || init?.type !== 'ObjectExpression') return

        const storyNameNode = init.properties.find(
          (prop: any) =>
            prop.type === 'Property' &&
            prop.key?.type === 'Identifier' &&
            (prop.key.name === 'name' || prop.key.name === 'storyName'),
        )
        if (storyNameNode === undefined) return

        const resolvedStoryName = storyNameFromExport(id.name)
        if (
          storyNameNode.type !== 'SpreadElement' &&
          storyNameNode.value?.type === 'Literal' &&
          storyNameNode.value.value === resolvedStoryName
        ) {
          context.report({
            node: storyNameNode,
            messageId: 'storyNameIsRedundant',
            fix: (fixer: any) => fixer.remove(storyNameNode),
          })
        }
      },
      // CSF2: Foo.storyName = 'Foo'
      AssignmentExpression(node: any) {
        if (node.parent?.type !== 'ExpressionStatement') return

        const left = node.left
        const right = node.right
        if (
          'property' in left &&
          left.property?.type === 'Identifier' &&
          left.object?.type !== 'MetaProperty' &&
          left.property.name === 'storyName'
        ) {
          if (!('name' in left.object) || !('value' in right)) return

          const propertyName = left.object.name
          const propertyValue = right.value
          const resolvedStoryName = storyNameFromExport(propertyName)

          if (propertyValue === resolvedStoryName) {
            context.report({
              node,
              messageId: 'storyNameIsRedundant',
              fix: (fixer: any) => fixer.remove(node),
            })
          }
        }
      },
    }
  },
}
