import {
  workflowReportKind,
  workflowReportMarker,
  workflowReportOutputName,
  workflowReportPathOutputName,
  workflowReportSchemaVersion,
} from './shared.ts'

type RunTasksBefore = (...tasks: [string, ...string[]]) => string

export const netlifyDeployStep = (runDevenvTasksBefore: RunTasksBefore) => ({
  id: 'deploy',
  name: 'Deploy storybooks to Netlify',
  shell: 'bash' as const,
  run: [
    'tmp_log="/tmp/netlify-storybook-deploy.log"',
    'rm -f "$tmp_log"',
    'workflow_report_dir="${RUNNER_TEMP:-/tmp}/workflow-reports"',
    'mkdir -p "$workflow_report_dir"',
    'workflow_report_path="$(mktemp "$workflow_report_dir/netlify-storybooks.XXXXXX.jsonl")"',
    'export WORKFLOW_REPORT_OUTPUT_FILE="$workflow_report_path"',
    'if [ -z "${NETLIFY_AUTH_TOKEN:-}" ]; then',
    '  deployed_at_utc="$(date -u +%Y-%m-%dT%H:%M:%SZ)"',
    '  workflow_report_json="$(jq -cn \\',
    `    --argjson schemaVersion ${workflowReportSchemaVersion} \\`,
    '    --arg tag WorkflowReportRecord \\',
    '    --arg id deploy-netlify-storybooks \\',
    `    --arg kind ${JSON.stringify(workflowReportKind)} \\`,
    '    --arg status skipped \\',
    '    --arg provider netlify \\',
    '    --arg target storybooks \\',
    '    --arg displayName "Storybooks" \\',
    '    --arg deployedAtUtc "$deployed_at_utc" \\',
    '    --arg message "Skipping Netlify deploy because NETLIFY_AUTH_TOKEN is not available." \\',
    '    \'{_tag: $tag, schemaVersion: $schemaVersion, id: $id, kind: $kind, subject: {id: $target, label: $displayName}, status: $status, title: ($displayName + " preview not deployed"), summary: $message, createdAtUtc: $deployedAtUtc, data: {provider: $provider, target: $target, displayName: $displayName, reason: $message}}\')"',
    '  printf "%s\\n" "$workflow_report_json" > "$workflow_report_path"',
    `  echo "${workflowReportMarker}$workflow_report_json"`,
    `  echo "${workflowReportPathOutputName}=$workflow_report_path" >> "$GITHUB_OUTPUT"`,
    `  printf '${workflowReportOutputName}=%s\\n' "$workflow_report_json" >> "$GITHUB_OUTPUT"`,
    '  echo "::notice::Skipping Netlify deploy (NETLIFY_AUTH_TOKEN not available)"',
    '  exit 0',
    'fi',
    'if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref }}" = "refs/heads/main" ]; then',
    `  ${runDevenvTasksBefore('netlify:deploy', '--show-output', '--input', 'type=prod')} 2>&1 | tee "$tmp_log"`,
    'elif [ "${{ github.event_name }}" = "pull_request" ]; then',
    `  ${runDevenvTasksBefore('netlify:deploy', '--show-output', '--input', 'type=pr', '--input', 'pr=${{ github.event.pull_request.number }}')} 2>&1 | tee "$tmp_log"`,
    'fi',
    'deploy_exit=${PIPESTATUS[0]}',
    'if [ "$deploy_exit" -ne 0 ]; then exit "$deploy_exit"; fi',
    'workflow_report_json=""',
    'if [ -s "$workflow_report_path" ]; then',
    '  workflow_report_json="$(tail -n 1 "$workflow_report_path")"',
    'fi',
    'if [ -z "$workflow_report_json" ]; then',
    `  workflow_report_json=$(grep -F ${JSON.stringify(workflowReportMarker)} "$tmp_log" | sed 's/^.*${workflowReportMarker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}//' | tail -n 1 || true)`,
    'fi',
    'if [ -n "$workflow_report_json" ]; then',
    '  workflow_report_json="$(printf "%s" "$workflow_report_json" | jq -c \'.\')"',
    '  printf "%s\\n" "$workflow_report_json" > "$workflow_report_path"',
    `  echo "${workflowReportMarker}$workflow_report_json"`,
    `  printf '${workflowReportOutputName}=%s\\n' "$workflow_report_json" >> "$GITHUB_OUTPUT"`,
    'fi',
    `echo "${workflowReportPathOutputName}=$workflow_report_path" >> "$GITHUB_OUTPUT"`,
  ].join('\n'),
})
