import {
  workflowReportKind,
  workflowReportMarker,
  workflowReportOutputName,
  workflowReportPathOutputName,
  workflowReportRuntimeModuleSetup,
  workflowReportSchemaVersion,
} from './shared.ts'

type RunTasksBefore = (...tasks: [string, ...string[]]) => string

export const netlifyDeployStep = (runDevenvTasksBefore: RunTasksBefore) => ({
  id: 'deploy',
  name: 'Deploy storybooks to Netlify',
  shell: 'bash' as const,
  run: [
    'tmp_log="/tmp/netlify-storybook-deploy.log"',
    'rm -f "$tmp_log"',
    'workflow_report_dir="${RUNNER_TEMP:-/tmp}/workflow-reports"',
    'mkdir -p "$workflow_report_dir"',
    'workflow_report_path="$(mktemp "$workflow_report_dir/netlify-storybooks.XXXXXX.jsonl")"',
    'export WORKFLOW_REPORT_OUTPUT_FILE="$workflow_report_path"',
    'if [ -z "${NETLIFY_AUTH_TOKEN:-}" ]; then',
    '  deployed_at_utc="$(date -u +%Y-%m-%dT%H:%M:%SZ)"',
    '  workflow_report_json="$(jq -cn \\',
    `    --argjson schemaVersion ${workflowReportSchemaVersion} \\`,
    '    --arg tag WorkflowReportRecord \\',
    '    --arg id deploy-netlify-storybooks \\',
    `    --arg kind ${JSON.stringify(workflowReportKind)} \\`,
    '    --arg status skipped \\',
    '    --arg provider netlify \\',
    '    --arg target storybooks \\',
    '    --arg displayName "Storybooks" \\',
    '    --arg deployedAtUtc "$deployed_at_utc" \\',
    '    --arg message "Skipping Netlify deploy because NETLIFY_AUTH_TOKEN is not available." \\',
    '    \'{_tag: $tag, schemaVersion: $schemaVersion, id: $id, kind: $kind, subject: {id: $target, label: $displayName}, status: $status, title: ($displayName + " preview not deployed"), summary: $message, createdAtUtc: $deployedAtUtc, data: {provider: $provider, target: $target, displayName: $displayName, reason: $message}}\')"',
    '  printf "%s\\n" "$workflow_report_json" > "$workflow_report_path"',
    `  echo "${workflowReportMarker}$workflow_report_json"`,
    `  echo "${workflowReportPathOutputName}=$workflow_report_path" >> "$GITHUB_OUTPUT"`,
    `  printf '${workflowReportOutputName}=%s\\n' "$workflow_report_json" >> "$GITHUB_OUTPUT"`,
    '  printf \'packages_json<<__NETLIFY_PACKAGES__\\n[]\\n__NETLIFY_PACKAGES__\\n\' >> "$GITHUB_OUTPUT"',
    '  echo "::notice::Skipping Netlify deploy (NETLIFY_AUTH_TOKEN not available)"',
    '  exit 0',
    'fi',
    'if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref }}" = "refs/heads/main" ]; then',
    `  ${runDevenvTasksBefore('netlify:deploy', '--show-output', '--input', 'type=prod')} 2>&1 | tee "$tmp_log"`,
    'elif [ "${{ github.event_name }}" = "pull_request" ]; then',
    `  ${runDevenvTasksBefore('netlify:deploy', '--show-output', '--input', 'type=pr', '--input', 'pr=${{ github.event.pull_request.number }}')} 2>&1 | tee "$tmp_log"`,
    'fi',
    'deploy_exit=${PIPESTATUS[0]}',
    'if [ "$deploy_exit" -ne 0 ]; then exit "$deploy_exit"; fi',
    "cat > /tmp/extract-netlify-preview-packages.mjs <<'EOF'",
    [
      "import { readFileSync } from 'node:fs'",
      '',
      'const [logPath] = process.argv.slice(2)',
      `const workflowReportMarker = ${JSON.stringify(workflowReportMarker)}`,
      'const prefixes = ["DEPLOY_TASK_METADATA: ", "NETLIFY_DEPLOY_METADATA: ", workflowReportMarker]',
      'const packages = readFileSync(logPath, "utf8")',
      '  .split("\\n")',
      '  .flatMap((line) => {',
      '    const prefix = prefixes.find((candidate) => line.includes(candidate))',
      '    if (!prefix) return []',
      '    const rawRecord = JSON.parse(line.slice(line.indexOf(prefix) + prefix.length))',
      '    if (rawRecord._tag === "WorkflowReportRecord" && rawRecord.kind === "deploy-preview" && rawRecord.data?.provider === "netlify" && rawRecord.status === "success") {',
      '      const primaryLink = rawRecord.links?.find((link) => link.primary === true) ?? rawRecord.links?.[0]',
      '      if (primaryLink === undefined) return []',
      '      return [{',
      '        packageName: rawRecord.subject?.label ?? rawRecord.subject?.id,',
      '        rawDeployUrl: rawRecord.data?.rawDeployUrl ?? primaryLink.url,',
      '        finalUrl: primaryLink.url,',
      '        deployedAtUtc: rawRecord.createdAtUtc,',
      '      }]',
      '    }',
      '    if (rawRecord.provider === "netlify") {',
      '      return [{',
      '        packageName: rawRecord.displayName ?? rawRecord.target,',
      '        rawDeployUrl: rawRecord.rawDeployUrl,',
      '        finalUrl: rawRecord.finalUrl,',
      '        deployedAtUtc: rawRecord.deployedAtUtc,',
      '      }]',
      '    }',
      '    if ("packageName" in rawRecord) return [rawRecord]',
      '    return []',
      '  })',
      'const dedupedPackages = [...new Map(packages.map((pkg) => [pkg.packageName, pkg])).values()]',
      'process.stdout.write(JSON.stringify(dedupedPackages))',
    ].join('\n'),
    'EOF',
    'packages_json="$(nix run nixpkgs#bun -- /tmp/extract-netlify-preview-packages.mjs "$tmp_log")"',
    'workflow_report_json=""',
    'if [ -s "$workflow_report_path" ]; then',
    '  workflow_report_json="$(tail -n 1 "$workflow_report_path")"',
    'fi',
    'if [ -z "$workflow_report_json" ]; then',
    `  workflow_report_json=$(grep -F ${JSON.stringify(workflowReportMarker)} "$tmp_log" | sed 's/^.*${workflowReportMarker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}//' | tail -n 1 || true)`,
    'fi',
    'if [ -n "$workflow_report_json" ]; then',
    '  workflow_report_json="$(printf "%s" "$workflow_report_json" | jq -c \'.\')"',
    '  printf "%s\\n" "$workflow_report_json" > "$workflow_report_path"',
    `  echo "${workflowReportMarker}$workflow_report_json"`,
    `  printf '${workflowReportOutputName}=%s\\n' "$workflow_report_json" >> "$GITHUB_OUTPUT"`,
    'fi',
    `echo "${workflowReportPathOutputName}=$workflow_report_path" >> "$GITHUB_OUTPUT"`,
    'printf \'packages_json<<__NETLIFY_PACKAGES__\\n%s\\n__NETLIFY_PACKAGES__\\n\' "$packages_json" >> "$GITHUB_OUTPUT"',
  ].join('\n'),
})

export const netlifyStorybookCommentStep = (site: string, deployModeScript: string) => ({
  name: 'Post storybook preview comment',
  if: '${{ !cancelled() }}',
  env: {
    GH_TOKEN: '${{ github.token }}',
    GH_REPO: '${{ github.repository }}',
    STORYBOOK_PREVIEW_PACKAGES_JSON: '${{ steps.deploy.outputs.packages_json }}',
    STORYBOOK_PREVIEW_WORKFLOW_REPORT: `\${{ steps.deploy.outputs.${workflowReportOutputName} }}`,
  },
  run: [
    `site="${site}"`,
    deployModeScript,
    'if [ "$label" = "prod" ]; then suffix=""; else suffix="-pr-${{ github.event.pull_request.number }}"; fi',
    'if [ "${{ github.event_name }}" = "pull_request" ]; then',
    '  commit_sha="${{ github.event.pull_request.head.sha }}"',
    'else',
    '  commit_sha="${{ github.sha }}"',
    'fi',
    'export STORYBOOK_PREVIEW_LABEL="$label"',
    'export STORYBOOK_PREVIEW_COMMIT_SHA="$commit_sha"',
    'export STORYBOOK_PREVIEW_SITE="$site"',
    'export STORYBOOK_PREVIEW_SUFFIX="$suffix"',
    'export STORYBOOK_PREVIEW_DEPLOYED_AT_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"',
    'comments_json="/tmp/storybook-preview-comments.json"',
    'if [ "${{ github.event_name }}" = "pull_request" ]; then',
    `  export NIX_CONFIG="\${NIX_CONFIG:+$NIX_CONFIG$'\\n'}access-tokens = github.com=\${GH_TOKEN}"`,
    '  nix run nixpkgs#gh -- api "repos/$GH_REPO/issues/${{ github.event.pull_request.number }}/comments" --paginate > "$comments_json"',
    'else',
    '  printf \'[]\' > "$comments_json"',
    'fi',
    "cat > /tmp/render-storybook-preview-comment.mjs <<'EOF'",
    [
      "import { readFileSync, writeFileSync } from 'node:fs'",
      "import { resolve } from 'node:path'",
      "import { pathToFileURL } from 'node:url'",
      '',
      'const commentTitle = "Storybook Previews"',
      'const noRecordsMessage = "No storybooks were deployed."',
      'const stateId = "storybook-preview"',
      '',
      'const [commentsPath, commentBodyPath, summaryPath, commentIdPath] = process.argv.slice(2)',
      'const runtimeModule = process.env.WORKFLOW_REPORT_RUNTIME_MODULE',
      'if (typeof runtimeModule !== "string" || runtimeModule.length === 0) throw new Error("WORKFLOW_REPORT_RUNTIME_MODULE is required")',
      'const {',
      '  decodeWorkflowReportRecord,',
      '  deriveWorkflowReportManagedState,',
      '  encodeWorkflowReportRecordLine,',
      '  findWorkflowReportManagedComment,',
      '  legacyStorybookPreviewManagedStateMigration,',
      '  renderWorkflowReportCommentBody,',
      '} = await import(pathToFileURL(resolve(runtimeModule)).href)',
      '',
      'const fail = (message) => {',
      '  throw new Error(message)',
      '}',
      '',
      'const expectObject = (value, path) => {',
      "  if (typeof value !== 'object' || value === null || Array.isArray(value)) {",
      '    fail(`${path} must be an object`)',
      '  }',
      '  return value',
      '}',
      '',
      'const expectArray = (value, path) => {',
      '  if (!Array.isArray(value)) {',
      '    fail(`${path} must be an array`)',
      '  }',
      '  return value',
      '}',
      '',
      'const expectString = (value, path) => {',
      "  if (typeof value !== 'string' || value.length === 0) {",
      '    fail(`${path} must be a non-empty string`)',
      '  }',
      '  return value',
      '}',
      '',
      'const expectUrl = (value, path) => {',
      '  const string = expectString(value, path)',
      "  if (!string.startsWith('https://')) {",
      '    fail(`${path} must start with https://`)',
      '  }',
      '  return string',
      '}',
      '',
      'const expectIsoUtc = (value, path) => {',
      '  const string = expectString(value, path)',
      '  if (!/^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{3})?Z$/.test(string) || Number.isNaN(Date.parse(string))) {',
      '    fail(`${path} must be a valid UTC ISO timestamp`)',
      '  }',
      '  return string',
      '}',
      '',
      'const validatePackageV3 = (value, path) => {',
      '  const record = expectObject(value, path)',
      '  return {',
      '    packageName: expectString(record.packageName, `${path}.packageName`),',
      '    rawDeployUrl: expectUrl(record.rawDeployUrl, `${path}.rawDeployUrl`),',
      '    finalUrl: expectUrl(record.finalUrl, `${path}.finalUrl`),',
      '    deployedAtUtc: expectIsoUtc(record.deployedAtUtc, `${path}.deployedAtUtc`),',
      '  }',
      '}',
      '',
      'const rawPackagesJson = process.env.STORYBOOK_PREVIEW_PACKAGES_JSON ?? ""',
      'if (rawPackagesJson.length === 0) {',
      '  const msg = "STORYBOOK_PREVIEW_PACKAGES_JSON is empty; the deploy step likely failed before producing output. Check the deploy step logs above."',
      '  console.error(msg)',
      '  process.exitCode = 1',
      '  writeFileSync(summaryPath, `## Storybook Previews\\n\\n> **Deploy failed.** ${msg}\\n`)',
      "  writeFileSync(commentBodyPath, '')",
      "  writeFileSync(commentIdPath, '')",
      '  process.exit(1)',
      '}',
      'const currentPackagesJson = rawPackagesJson',
      'const fallbackDeployedAtUtc = expectIsoUtc(process.env.STORYBOOK_PREVIEW_DEPLOYED_AT_UTC, "STORYBOOK_PREVIEW_DEPLOYED_AT_UTC")',
      '',
      'const currentPackages = expectArray(JSON.parse(currentPackagesJson), "currentPackages").map((pkg, index) =>',
      '  validatePackageV3(pkg, `currentPackages[${index}]`),',
      ')',
      '',
      'const createdAtUtc = currentPackages.reduce(',
      '  (latest, pkg) => (pkg.deployedAtUtc > latest ? pkg.deployedAtUtc : latest),',
      '  fallbackDeployedAtUtc,',
      ')',
      '',
      'const reportFromPackage = (pkg) => decodeWorkflowReportRecord({',
      '  _tag: "WorkflowReportRecord",',
      '  schemaVersion: 1,',
      '  id: `deploy-netlify-${pkg.packageName}`,',
      '  kind: "deploy-preview",',
      '  subject: { id: pkg.packageName, label: pkg.packageName },',
      '  status: "success",',
      '  title: `${pkg.packageName} preview deployed`,',
      '  summary: "Preview is ready",',
      '  createdAtUtc: pkg.deployedAtUtc,',
      '  links: [{ label: "Preview", url: pkg.finalUrl, primary: true }],',
      '  data: {',
      '    provider: "netlify",',
      '    target: pkg.packageName,',
      '    displayName: pkg.packageName,',
      '    rawDeployUrl: pkg.rawDeployUrl,',
      '    finalUrl: pkg.finalUrl,',
      '    deployedAtUtc: pkg.deployedAtUtc,',
      '  },',
      '})',
      '',
      'const reportsFromPackages = currentPackages.map(reportFromPackage)',
      'const rawWorkflowReport = process.env.STORYBOOK_PREVIEW_WORKFLOW_REPORT ?? ""',
      'const currentReports = reportsFromPackages.length > 0',
      '  ? reportsFromPackages',
      '  : rawWorkflowReport.length > 0',
      '    ? [decodeWorkflowReportRecord(JSON.parse(rawWorkflowReport))]',
      '    : []',
      '',
      'for (const report of currentReports) {',
      '  console.log(encodeWorkflowReportRecordLine(report))',
      '}',
      '',
      "const comments = JSON.parse(readFileSync(commentsPath, 'utf8'))",
      'if (!Array.isArray(comments)) fail("comments response must be an array")',
      '',
      'const commitSha = expectString(process.env.STORYBOOK_PREVIEW_COMMIT_SHA, "STORYBOOK_PREVIEW_COMMIT_SHA")',
      'const modeLabel = expectString(process.env.STORYBOOK_PREVIEW_LABEL, "STORYBOOK_PREVIEW_LABEL")',
      'const existingComment = findWorkflowReportManagedComment(comments, {',
      '  stateId,',
      '  migrations: [legacyStorybookPreviewManagedStateMigration],',
      '})',
      'const state = deriveWorkflowReportManagedState({',
      '  stateId,',
      '  priorState: existingComment?.state,',
      '  entryId: commitSha,',
      '  entryLabel: modeLabel,',
      '  createdAtUtc,',
      '  records: currentReports,',
      '})',
      'const body = renderWorkflowReportCommentBody({ title: commentTitle, noRecordsMessage, state })',
      'const visibleBody = body.slice(0, body.indexOf("<!-- workflow-report:managed -->")).trimEnd() + "\\n"',
      'writeFileSync(commentBodyPath, body)',
      'writeFileSync(summaryPath, visibleBody)',
      'writeFileSync(commentIdPath, existingComment?.id ?? "")',
    ].join('\n'),
    'EOF',
    ...workflowReportRuntimeModuleSetup,
    'nix run nixpkgs#bun -- /tmp/render-storybook-preview-comment.mjs "$comments_json" /tmp/storybook-preview-comment.md "$GITHUB_STEP_SUMMARY" /tmp/storybook-preview-comment-id.txt',
    'comment_id="$(cat /tmp/storybook-preview-comment-id.txt)"',
    'if [ ! -s /tmp/storybook-preview-comment.md ]; then',
    '  exit 0',
    'fi',
    "node -e \"const fs=require('node:fs'); fs.writeFileSync(process.argv[2], JSON.stringify({ body: fs.readFileSync(process.argv[1], 'utf8') }))\" /tmp/storybook-preview-comment.md /tmp/storybook-preview-comment-payload.json",
    `export NIX_CONFIG="\${NIX_CONFIG:+$NIX_CONFIG$'\\n'}access-tokens = github.com=\${GH_TOKEN}"`,
    'if [ "${{ github.event_name }}" != "pull_request" ]; then',
    '  exit 0',
    'fi',
    'if [ -n "$comment_id" ]; then',
    '  nix run nixpkgs#gh -- api "repos/$GH_REPO/issues/comments/$comment_id" --method PATCH --input /tmp/storybook-preview-comment-payload.json >/dev/null',
    'else',
    '  nix run nixpkgs#gh -- api "repos/$GH_REPO/issues/${{ github.event.pull_request.number }}/comments" --method POST --input /tmp/storybook-preview-comment-payload.json >/dev/null',
    'fi',
  ].join('\n'),
})
