[package]
name = "buck2-archive-tool"
workspace = "../.."
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "buck2-archive-tool"
path = "src/main.rs"

[dependencies]
buck2-tool-core = { path = "../core" }
clap = { version = "4", features = ["derive"] }
flate2 = "1"
tar = { version = "0.4", default-features = false }

[dev-dependencies]
tempfile.workspace = true
