python_library(
    name = "closure_tool_lib",
    srcs = ["closure_tool.py"],
    visibility = ["PUBLIC"],
)

python_binary(
    name = "closure_tool",
    main_module = "buck2.tools.closure_tool",
    deps = [":closure_tool_lib"],
    visibility = ["PUBLIC"],
)

python_test(
    name = "closure_tool_test",
    srcs = ["closure_tool_test.py"],
    deps = [":closure_tool_lib"],
)

python_library(
    name = "portable_toolchain_lib",
    srcs = ["portable_toolchain.py"],
    visibility = ["PUBLIC"],
)

python_binary(
    name = "portable_toolchain_bootstrap",
    main_module = "buck2.tools.portable_toolchain",
    deps = [":portable_toolchain_lib"],
    visibility = ["PUBLIC"],
)

python_test(
    name = "portable_toolchain_test",
    srcs = ["portable_toolchain_test.py"],
    deps = [":portable_toolchain_lib"],
)

python_library(
    name = "package_evidence_tool_lib",
    srcs = ["package_evidence.py"],
    visibility = ["PUBLIC"],
)

python_binary(
    name = "package_evidence_tool",
    main_module = "buck2.tools.package_evidence",
    deps = [":package_evidence_tool_lib"],
    visibility = ["PUBLIC"],
)

python_test(
    name = "package_evidence_tool_test",
    srcs = ["package_evidence_test.py"],
    deps = [":package_evidence_tool_lib"],
)

python_library(
    name = "typescript_cli_builder_lib",
    srcs = ["typescript_cli.py"],
    visibility = ["PUBLIC"],
)

export_file(
    name = "typescript_cli_builder_source",
    src = "typescript_cli.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "typescript_cli_builder",
    main_module = "buck2.tools.typescript_cli",
    deps = [":typescript_cli_builder_lib"],
    visibility = ["PUBLIC"],
)

python_test(
    name = "typescript_cli_builder_test",
    srcs = ["typescript_cli_test.py"],
    deps = [":typescript_cli_builder_lib"],
)

python_library(
    name = "native_binary_artifact_builder_lib",
    srcs = ["native_binary_artifact.py"],
    visibility = ["PUBLIC"],
)

export_file(
    name = "native_binary_artifact_builder_source",
    src = "native_binary_artifact.py",
    visibility = ["PUBLIC"],
)

python_binary(
    name = "native_binary_artifact_builder",
    main_module = "buck2.tools.native_binary_artifact",
    deps = [":native_binary_artifact_builder_lib"],
    visibility = ["PUBLIC"],
)

python_test(
    name = "native_binary_artifact_builder_test",
    srcs = ["native_binary_artifact_test.py"],
    deps = [":native_binary_artifact_builder_lib"],
)
