python_library(
    name = "closure_tool_lib",
    srcs = ["closure_tool.py"],
    visibility = ["PUBLIC"],
)

python_binary(
    name = "closure_tool",
    main_module = "buck2.tools.closure_tool",
    deps = [":closure_tool_lib"],
    visibility = ["PUBLIC"],
)

python_test(
    name = "closure_tool_test",
    srcs = ["closure_tool_test.py"],
    deps = [":closure_tool_lib"],
)

python_library(
    name = "portable_toolchain_lib",
    srcs = ["portable_toolchain.py"],
    visibility = ["PUBLIC"],
)

python_binary(
    name = "portable_toolchain_bootstrap",
    main_module = "buck2.tools.portable_toolchain",
    deps = [":portable_toolchain_lib"],
    visibility = ["PUBLIC"],
)

python_test(
    name = "portable_toolchain_test",
    srcs = ["portable_toolchain_test.py"],
    deps = [":portable_toolchain_lib"],
)

python_library(
    name = "package_evidence_tool_lib",
    srcs = ["package_evidence.py"],
    visibility = ["PUBLIC"],
)

python_binary(
    name = "package_evidence_tool",
    main_module = "buck2.tools.package_evidence",
    deps = [":package_evidence_tool_lib"],
    visibility = ["PUBLIC"],
)

python_test(
    name = "package_evidence_tool_test",
    srcs = ["package_evidence_test.py"],
    deps = [":package_evidence_tool_lib"],
)
