/**
 * Schema-as-code config for the demo.
 *
 * Declares the databases whose typed Effect schemas are generated by:
 *
 *   notion schema generate-config
 *
 * One command regenerates the bindings for EVERY database listed here.
 *
 * In a real project you would install `@overeng/notion-cli` and get full
 * type-safety + autocomplete from its config helpers:
 *
 *   import { defineConfig, file } from '@overeng/notion-cli/config'
 *   export default defineConfig({ databases: { 'db-id': { output: file('tasks.ts') } } })
 *
 * This demo lives inside the source tree (the CLI isn't installed as a resolvable
 * dependency here), so it exports a plain config object instead and reads the
 * synthetic ids created by demo/schema/setup.sh from ../.demo-state — so this
 * committed file never hard-codes a throwaway id.
 */
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const id = (name: string): string =>
  readFileSync(join(here, '..', '.demo-state', name), 'utf8').trim()

export default {
  // Defaults applied to every database below.
  defaults: {
    includeWrite: true, // write schemas for create/update
    includeApi: true, // typed database API wrapper
    typedOptions: true, // literal-union types for select/status/multi_select
    schemaMeta: false, // keep fields one-line + JSDoc (drift-diff friendly, readable)
  },
  databases: {
    [id('tasks-db-id')]: { output: 'schema.gen.ts', name: 'Tasks' },
    [id('people-db-id')]: { output: 'people.gen.ts', name: 'People' },
  },
}
