//! Event-log adapter: direct, streaming decode of Buck2 be6971d4
//! `*_events.pb.zst` logs into linked critical and full OTLP trace views.
//! No Buck daemon or `buck2 log show` is needed, and truncated logs decode
//! up to their last complete record.
//! Ingest fails if any trace or metric chunk cannot be durably spooled, so
//! callers can retain the native logs for a later retry.
use clap::{Parser, Subcommand};
use prost::Message;
use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use std::{
    collections::{BTreeMap, HashMap, HashSet},
    fs::{self, File, OpenOptions},
    io::{self, BufReader, Read, Write},
    path::{Path, PathBuf},
    time::{Duration, Instant, SystemTime, UNIX_EPOCH},
};

// Generated by proto/generate from the vendored protos; do not edit.
#[allow(dead_code, clippy::all, clippy::pedantic)]
mod gen {
    pub mod buck {
        pub mod daemon {
            include!("gen/buck.daemon.rs");
        }
        pub mod data {
            include!("gen/buck.data.rs");
            pub mod error {
                include!("gen/buck.data.error.rs");
            }
        }
        pub mod host_sharing {
            include!("gen/buck.host_sharing.rs");
        }
        pub mod subscription {
            include!("gen/buck.subscription.rs");
        }
    }
}
use gen::buck::{
    daemon::{command_progress, CommandProgress},
    data::{self, buck_event, instant_event, span_end_event, span_start_event},
};

#[derive(Parser)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}
#[derive(Subcommand)]
enum Command {
    Ingest {
        #[arg(required = true)]
        logs: Vec<PathBuf>,
        #[arg(long)]
        sidecar: Option<PathBuf>,
        /// Also write standalone OTLP JSON files for inspection.
        #[arg(long)]
        out: Option<PathBuf>,
        #[arg(long)]
        spool_dir: Option<PathBuf>,
    },
    /// Retry pending OTLP chunks without re-decoding native event logs.
    Export {
        #[arg(long)]
        spool_dir: Option<PathBuf>,
        /// Upper bound for one OTLP request, connect through response body.
        #[arg(long, default_value_t = 5)]
        request_timeout_secs: u64,
        /// Upper bound for sending pending chunks in this invocation.
        #[arg(long, default_value_t = 30)]
        export_budget_secs: u64,
    },
}

/// Parses the command line and runs it; the binary maps errors to exit 1.
pub fn main_entry() -> Result<(), Box<dyn std::error::Error>> {
    run(Cli::parse())
}
fn run(cli: Cli) -> Result<(), Box<dyn std::error::Error>> {
    match cli.command {
        Command::Ingest {
            logs,
            sidecar,
            out,
            spool_dir,
        } => ingest(
            &logs,
            sidecar.as_ref(),
            out.as_ref(),
            &spool_directory(spool_dir),
        ),
        Command::Export {
            spool_dir,
            request_timeout_secs,
            export_budget_secs,
        } => {
            drain_pending(
                &spool_directory(spool_dir),
                Duration::from_secs(request_timeout_secs),
                Duration::from_secs(export_budget_secs),
            );
            Ok(())
        }
    }
}

fn spool_directory(explicit: Option<PathBuf>) -> PathBuf {
    explicit.unwrap_or_else(|| {
        std::env::var_os("OTEL_SPAN_SPOOL_DIR").map_or_else(
            || PathBuf::from(".devenv/otel/buck2-events/pending"),
            |parent| PathBuf::from(parent).join("pending"),
        )
    })
}

fn ingest(
    logs: &[PathBuf],
    sidecar: Option<&PathBuf>,
    out: Option<&PathBuf>,
    spool_dir: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let sidecars = if let Some(p) = sidecar {
        match fs::read_to_string(p) {
            Ok(lines) => lines
                .lines()
                .filter_map(|l| {
                    let (uuid, parent) = l.split_once(' ')?;
                    parse_traceparent(parent).map(|(trace, span)| (uuid.to_string(), (trace, span)))
                })
                .collect::<HashMap<_, _>>(),
            Err(e) if e.kind() == io::ErrorKind::NotFound => HashMap::new(),
            Err(e) => return Err(e.into()),
        }
    } else {
        HashMap::new()
    };
    if let Some(p) = out {
        fs::create_dir_all(p)?;
    }
    fs::create_dir_all(spool_dir)?;
    let identity_attrs = identity_attributes(|name| std::env::var(name).ok());
    for (index, log) in logs.iter().enumerate() {
        let model = decode(log)?;
        let parent = sidecars.get(&model.uuid);
        let views = make_views(&model, parent);
        for (kind, trace_id, spans) in views {
            let mut resource_attrs = vec![
                attr("service.name", "effect-utils-buck2"),
                attr("buck2.build_id", &model.uuid),
            ];
            resource_attrs.extend(model.resource_attrs.iter().cloned());
            resource_attrs.extend(identity_attrs.iter().cloned());
            let resource = json!({"attributes": resource_attrs});
            for (chunk_index, chunk) in chunks(&spans, &resource)?.iter().enumerate() {
                if let Some(dir) = out {
                    fs::write(
                        dir.join(format!("{index}-{kind}-{chunk_index}.json")),
                        chunk,
                    )?;
                }
                spool_chunk(spool_dir, "traces", chunk).map_err(|error| {
                    io::Error::new(
                        error.kind(),
                        format!("could not spool OTLP trace chunk: {error}"),
                    )
                })?;
            }
            println!(
                "{}",
                json!({"log": log, "view": kind, "traceId": trace_id, "spans": spans.len(), "truncated": model.truncated, "stop_reason": model.stop_reason, "unknown_fields": model.unknown_fields})
            );
        }
        let metrics = metric_payload(&model);
        if let Some(dir) = out {
            fs::write(dir.join(format!("{index}-metrics.json")), &metrics)?;
        }
        spool_chunk(spool_dir, "metrics", &metrics).map_err(|error| {
            io::Error::new(
                error.kind(),
                format!("could not spool OTLP metrics chunk: {error}"),
            )
        })?;
    }
    Ok(())
}

fn identity_attributes(mut env: impl FnMut(&str) -> Option<String>) -> Vec<Value> {
    let mut attrs = Vec::new();
    let run_id = env("PIPELINE_RUN_ID").filter(|value| !value.is_empty());
    if let Some(run_id) = &run_id {
        attrs.push(attr("cicd.pipeline.run.id", run_id));
    }
    let provider = env("CI_PROVIDER")
        .filter(|value| !value.is_empty())
        .or_else(|| {
            run_id
                .as_deref()
                .and_then(|id| id.strip_prefix("ci/"))
                .and_then(|tail| tail.split('/').next())
                .filter(|value| !value.is_empty())
                .map(str::to_owned)
        });
    if let Some(provider) = provider {
        attrs.push(attr("vcs.provider.name", provider));
    }
    if let Some(fork) = env("PIPELINE_FORK").as_deref() {
        match fork {
            "true" => attrs.push(bool_attr("buck2.vcs.change.is_fork", true)),
            "false" => attrs.push(bool_attr("buck2.vcs.change.is_fork", false)),
            _ => {}
        }
    }
    for (variable, attribute) in [
        ("VCS_CHANGE_ID", "vcs.change.id"),
        ("VCS_REF_HEAD_REVISION", "vcs.ref.head.revision"),
        ("VCS_REF_BASE_REVISION", "vcs.ref.base.revision"),
        ("BUCK2_VCS_MERGE_REVISION", "buck2.vcs.merge.revision"),
    ] {
        if let Some(value) = env(variable).filter(|value| !value.is_empty()) {
            attrs.push(attr(attribute, value));
        }
    }
    attrs
}
/// A stalled collector must never hold the calling task: every request is
/// bounded end to end (connect, send, response, body).
fn otlp_agent(timeout: Duration) -> ureq::Agent {
    ureq::Agent::config_builder()
        .timeout_global(Some(timeout))
        .build()
        .into()
}

const MAX_OTLP_BODY: usize = 3_300_000;
const DESTINATION: &str = "OTEL_EXPORTER_OTLP_ENDPOINT";

fn sha256_hex(body: &[u8]) -> String {
    use std::fmt::Write as _;
    let digest = Sha256::digest(body);
    let mut id = String::with_capacity(64);
    for byte in digest {
        write!(id, "{byte:02x}").expect("write SHA-256 digest");
    }
    id
}

fn spool_chunk(dir: &Path, signal: &str, body: &[u8]) -> io::Result<PathBuf> {
    if body.len() > MAX_OTLP_BODY {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            "OTLP chunk exceeds collector limit",
        ));
    }
    fs::create_dir_all(dir)?;
    let id = sha256_hex(body);
    let name = format!("{id}.{signal}.chunk");
    let target = dir.join(&name);
    if target.exists() && read_chunk(&target).is_ok_and(|existing| existing == body) {
        return Ok(target);
    }
    let meta = json!({"signal":signal,"byte_count":body.len(),"destination":DESTINATION,"id":id});
    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let temporary = dir.join(format!(".{name}.{}.{}.tmp", std::process::id(), now));
    let result = (|| {
        let mut file = OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&temporary)?;
        serde_json::to_writer(&mut file, &meta)?;
        file.write_all(b"\n")?;
        file.write_all(body)?;
        file.sync_all()?;
        fs::rename(&temporary, &target)?;
        File::open(dir)?.sync_all()?;
        Ok::<(), Box<dyn std::error::Error>>(())
    })();
    if let Err(error) = result {
        let _ = fs::remove_file(&temporary);
        return Err(io::Error::other(error.to_string()));
    }
    Ok(target)
}

fn read_chunk(path: &Path) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
    if fs::metadata(path)?.len() > (MAX_OTLP_BODY + 4096) as u64 {
        return Err("OTLP chunk exceeds collector body limit".into());
    }
    let mut bytes = fs::read(path)?;
    let split = bytes
        .iter()
        .position(|byte| *byte == b'\n')
        .ok_or("missing OTLP chunk header")?;
    let meta: Value = serde_json::from_slice(&bytes[..split])?;
    let body = &bytes[split + 1..];
    let filename = path
        .file_name()
        .and_then(|s| s.to_str())
        .ok_or("invalid chunk name")?;
    let signal = meta["signal"].as_str().ok_or("invalid OTLP signal")?;
    let id = sha256_hex(body);
    if !matches!(signal, "traces" | "metrics")
        || meta["id"].as_str() != Some(id.as_str())
        || meta["destination"].as_str() != Some(DESTINATION)
        || meta["byte_count"].as_u64() != Some(body.len() as u64)
        || filename != format!("{id}.{signal}.chunk")
        || body.len() > MAX_OTLP_BODY
    {
        return Err("invalid OTLP chunk metadata or body".into());
    }
    bytes.copy_within(split + 1.., 0);
    bytes.truncate(bytes.len() - split - 1);
    Ok(bytes)
}

fn export(
    agent: &ureq::Agent,
    url: &str,
    signal: &str,
    chunk: &[u8],
) -> Result<(), Box<dyn std::error::Error>> {
    let response = agent
        .post(url)
        .header("content-type", "application/json")
        .send(chunk)?;
    let body = response.into_body().read_to_vec()?;
    let result: Value = serde_json::from_slice(&body)?;
    let response = result.as_object().ok_or("invalid OTLP response object")?;
    let partial = response
        .get("partialSuccess")
        .or_else(|| response.get("partial_success"));
    if let Some(partial) = partial {
        let partial = partial.as_object().ok_or("invalid OTLP partial success")?;
        let (camel, snake, unit) = if signal == "metrics" {
            ("rejectedDataPoints", "rejected_data_points", "data points")
        } else {
            ("rejectedSpans", "rejected_spans", "spans")
        };
        let rejected = partial.get(camel).or_else(|| partial.get(snake));
        let rejected = match rejected {
            None => 0,
            Some(Value::String(n)) => n.parse::<u64>()?,
            Some(Value::Number(n)) => n.as_u64().ok_or("invalid OTLP rejection count")?,
            _ => return Err("invalid OTLP rejection count".into()),
        };
        if rejected > 0 {
            let message = partial
                .get("errorMessage")
                .or_else(|| partial.get("error_message"))
                .and_then(Value::as_str)
                .unwrap_or("");
            return Err(format!("OTLP partial rejection: {rejected} {unit}; {message}").into());
        }
    }
    Ok(())
}

fn export_allowed(
    github_actions: bool,
    run_id: Option<&str>,
    mode: Option<&str>,
    trusted: Option<&str>,
) -> bool {
    let ci_run = github_actions || run_id.is_some_and(|run| run.starts_with("ci/"));
    !ci_run || (mode == Some("upload") && trusted == Some("true"))
}

fn drain_pending(dir: &Path, request_timeout: Duration, budget: Duration) {
    if !export_allowed(
        std::env::var("GITHUB_ACTIONS").as_deref() == Ok("true"),
        std::env::var("PIPELINE_RUN_ID").ok().as_deref(),
        std::env::var("CI_EVIDENCE_MODE").ok().as_deref(),
        std::env::var("PIPELINE_TRUSTED").ok().as_deref(),
    ) {
        return;
    }
    let Ok(endpoint) = std::env::var(DESTINATION) else {
        eprintln!("buck2-events: OTLP endpoint unavailable; retaining pending chunks");
        return;
    };
    if endpoint.is_empty() {
        eprintln!("buck2-events: OTLP endpoint unavailable; retaining pending chunks");
        return;
    }
    let url = format!(
        "{}/v1/traces",
        endpoint
            .trim_end_matches('/')
            .trim_end_matches("/v1/traces")
    );
    drain_to_url(dir, &url, request_timeout, budget);
}

fn drain_to_url(dir: &Path, url: &str, request_timeout: Duration, budget: Duration) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    let deadline = Instant::now() + budget;
    let agent = otlp_agent(request_timeout);
    let metric_url = format!("{}/v1/metrics", url.trim_end_matches("/v1/traces"));
    let mut paths: Vec<_> = entries
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|e| e == "chunk"))
        .collect();
    paths.sort();
    for path in paths {
        if Instant::now() >= deadline {
            eprintln!("buck2-events: OTLP export budget exhausted; retaining pending chunks");
            break;
        }
        let body = match read_chunk(&path) {
            Ok(body) => body,
            Err(error) => {
                eprintln!("buck2-events: retaining {}: {error}", path.display());
                continue;
            }
        };
        let metrics = path
            .file_name()
            .and_then(|name| name.to_str())
            .is_some_and(|name| name.ends_with(".metrics.chunk"));
        let (route, signal) = if metrics {
            (metric_url.as_str(), "metrics")
        } else {
            (url, "traces")
        };
        for attempt in 0..2 {
            match export(&agent, route, signal, &body) {
                Ok(()) => {
                    if let Err(error) = fs::remove_file(&path) {
                        eprintln!(
                            "buck2-events: could not acknowledge {}: {error}",
                            path.display()
                        );
                    }
                    break;
                }
                Err(error)
                    if attempt == 0 && Instant::now() + Duration::from_millis(100) < deadline =>
                {
                    eprintln!("buck2-events: {}: {error}; retrying", path.display());
                    std::thread::sleep(Duration::from_millis(100));
                }
                Err(error) => {
                    eprintln!("buck2-events: retaining {}: {error}", path.display());
                    break;
                }
            }
        }
    }
}
fn parse_traceparent(s: &str) -> Option<(String, String)> {
    let parts: Vec<_> = s.split('-').collect();
    if parts.len() != 4
        || parts[0] != "00"
        || parts[1].len() != 32
        || parts[2].len() != 16
        || parts[3].len() != 2
        || !parts
            .iter()
            .all(|v| v.bytes().all(|b| b.is_ascii_hexdigit()))
        || parts[1].bytes().all(|b| b == b'0')
        || parts[2].bytes().all(|b| b == b'0')
    {
        return None;
    }
    Some((parts[1].to_owned(), parts[2].to_owned()))
}
fn hash_hex(input: &str, length: usize) -> String {
    use std::fmt::Write;
    let digest = Sha256::digest(input.as_bytes());
    let mut hex = String::with_capacity(length);
    for byte in digest.iter().take(length / 2) {
        write!(hex, "{byte:02x}").expect("write hex");
    }
    hex
}
fn span_id(uuid: &str, id: u64) -> String {
    hash_hex(&format!("{uuid}:{id}"), 16)
}
fn timestamp(t: Option<&prost_types::Timestamp>) -> u64 {
    t.map_or(0, |t| {
        (t.seconds.max(0) as u64)
            .saturating_mul(1_000_000_000)
            .saturating_add(t.nanos.max(0) as u64)
    })
}
fn duration_ns(duration: &prost_types::Duration) -> u64 {
    (duration.seconds.max(0) as u64)
        .saturating_mul(1_000_000_000)
        .saturating_add(duration.nanos.max(0) as u64)
}
fn read_record<R: Read>(reader: &mut R, buf: &mut Vec<u8>) -> io::Result<Option<()>> {
    let mut len = 0u64;
    for shift in (0..70).step_by(7) {
        let mut byte = [0];
        match reader.read_exact(&mut byte) {
            Ok(()) => {}
            Err(e) if e.kind() == io::ErrorKind::UnexpectedEof && shift == 0 => return Ok(None),
            Err(e) => return Err(e),
        }
        if shift == 63 && byte[0] > 1 {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                "invalid record length",
            ));
        }
        len |= u64::from(byte[0] & 127) << shift;
        if byte[0] & 128 == 0 {
            if len > 64 * 1024 * 1024 {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidData,
                    "record exceeds 64 MiB",
                ));
            }
            buf.resize(len as usize, 0);
            reader.read_exact(buf)?;
            return Ok(Some(()));
        }
    }
    Err(io::Error::new(io::ErrorKind::InvalidData, "invalid varint"))
}

/// Resource bounds for untrusted logs. Crossing one stops decoding at the
/// last complete record and records the reason; the prefix is still exported.
#[derive(Clone, Copy)]
struct Limits {
    compressed_bytes: u64,
    decompressed_bytes: u64,
    records: u64,
    spans: usize,
    /// Critical-path span ids read across all BuildGraphInfo events.
    critical_ids: u64,
}
impl Default for Limits {
    fn default() -> Self {
        // The largest observed log is 0.7 MB compressed, 7.3 MB decoded and
        // 12.6k spans; peak RSS scales with spans (~20 KB each).
        Limits {
            compressed_bytes: 256 << 20,
            decompressed_bytes: 1 << 30,
            records: 5_000_000,
            spans: 150_000,
            critical_ids: 1_000_000,
        }
    }
}

const ZSTD_MAGIC: [u8; 4] = [0x28, 0xb5, 0x2f, 0xfd];
const ZSTD_MAX_BLOCK: usize = 128 * 1024;

/// Makes the first zstd frame decodable up to its last complete block.
///
/// A Buck log cut mid-write ends inside a block. Streaming decoders keep the
/// last window (4 MiB for Buck logs) undrained until the frame finishes, so a
/// cut frame would otherwise lose that whole tail, which is often the entire
/// log. Ending the frame after the last complete block with an empty raw last
/// block lets the decoder drain everything that was actually written.
/// Returns the sealed input and the reason it was sealed, if it was.
fn seal_frame(mut bytes: Vec<u8>) -> Result<(Vec<u8>, Option<String>), String> {
    if bytes.len() < 5 || bytes[..4] != ZSTD_MAGIC {
        return Err("not a zstd frame".into());
    }
    let descriptor = bytes[4];
    let single_segment = descriptor & 0x20 != 0;
    let checksum = descriptor & 0x04 != 0;
    let content_size_bytes = match descriptor >> 6 {
        0 => usize::from(single_segment),
        1 => 2,
        2 => 4,
        _ => 8,
    };
    let mut position = 5
        + usize::from(!single_segment)
        + [0, 1, 2, 4][usize::from(descriptor & 3)]
        + content_size_bytes;
    if position > bytes.len() {
        return Err("zstd frame header is incomplete".into());
    }
    let reason = loop {
        let Some(header) = bytes.get(position..position + 3) else {
            break "truncated: zstd frame ends inside a block header".to_string();
        };
        let header = u32::from(header[0]) | u32::from(header[1]) << 8 | u32::from(header[2]) << 16;
        let (last, kind, size) = (header & 1 == 1, (header >> 1) & 3, (header >> 3) as usize);
        if kind == 3 || size > ZSTD_MAX_BLOCK {
            break format!("corrupt: invalid zstd block header at byte {position}");
        }
        let content = if kind == 1 { 1 } else { size };
        if position + 3 + content > bytes.len() {
            break "truncated: zstd frame ends inside a block".to_string();
        }
        position += 3 + content;
        if last {
            if checksum {
                position += 4;
            }
            if position < bytes.len() {
                return Ok((
                    bytes,
                    Some("unsupported: data after the first zstd frame ignored".into()),
                ));
            }
            return Ok((bytes, None));
        }
    };
    bytes.truncate(position);
    // Empty raw block flagged last; a declared checksum is not verified.
    bytes.extend_from_slice(&[1, 0, 0]);
    if checksum {
        bytes.extend_from_slice(&[0; 4]);
    }
    Ok((bytes, Some(reason)))
}

/// Caps the decompressed stream so a small, highly compressible log cannot
/// grow without bound; crossing the cap fails with `FileTooLarge`.
struct Bounded<R> {
    inner: R,
    remaining: u64,
}
impl<R: Read> Read for Bounded<R> {
    fn read(&mut self, buf: &mut [u8]) -> io::Result<usize> {
        if self.remaining == 0 {
            let mut probe = [0];
            return match self.inner.read(&mut probe)? {
                0 => Ok(0),
                _ => Err(io::Error::new(
                    io::ErrorKind::FileTooLarge,
                    "decompressed size limit reached",
                )),
            };
        }
        let allowed = buf
            .len()
            .min(usize::try_from(self.remaining).unwrap_or(usize::MAX));
        let read = self.inner.read(&mut buf[..allowed])?;
        self.remaining -= read as u64;
        Ok(read)
    }
}

struct Span {
    id: u64,
    parent: u64,
    start: u64,
    end: u64,
    name: String,
    attrs: Vec<Value>,
    critical: bool,
    action: bool,
    cache_hit: bool,
    ended: bool,
    execution_ns: Option<u64>,
    queue_ns: Option<u64>,
}
struct Model {
    uuid: String,
    spans: Vec<Span>,
    resource_attrs: Vec<Value>,
    critical_ns: Option<u64>,
    truncated: bool,
    /// Why decoding stopped before a clean end: corruption or a resource limit.
    stop_reason: Option<String>,
    unknown_fields: usize,
}
fn attr(key: &str, value: impl ToString) -> Value {
    json!({"key":key,"value":{"stringValue":value.to_string()}})
}
fn int_attr(key: &str, value: impl ToString) -> Value {
    json!({"key":key,"value":{"intValue":value.to_string()}})
}
fn bool_attr(key: &str, value: bool) -> Value {
    json!({"key":key,"value":{"boolValue":value}})
}
fn snake(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for (i, c) in s.chars().enumerate() {
        if c.is_ascii_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(c.to_ascii_lowercase());
    }
    out
}
fn action_kind(code: i32) -> &'static str {
    match code {
        1 => "local",
        2 => "remote",
        3 => "action_cache",
        4 => "simple",
        6 => "deferred",
        7 => "local_dep_file",
        8 => "local_worker",
        9 => "remote_dep_file_cache",
        10 => "local_action_cache",
        11 => "remote_worker",
        _ => "not_set",
    }
}
fn target_attrs(attrs: &mut Vec<Value>, target: &data::ConfiguredTargetLabel) {
    if let Some(label) = &target.label {
        attrs.push(attr(
            "buck2.target",
            format!("{}:{}", label.package, label.name),
        ));
    }
    if let Some(configuration) = &target.configuration {
        attrs.push(attr("buck2.configuration", &configuration.full_name));
    }
}
fn start_shape(start: span_start_event::Data) -> (String, Vec<Value>, bool) {
    let mut attrs = Vec::new();
    let (kind, detail, action) = match start {
        span_start_event::Data::Command(c) => {
            attrs.push(attr(
                "buck2.command",
                c.cli_args
                    .iter()
                    .skip(1)
                    .cloned()
                    .collect::<Vec<_>>()
                    .join(" "),
            ));
            (
                "command",
                c.cli_args.get(1).cloned().unwrap_or_else(|| "build".into()),
                false,
            )
        }
        span_start_event::Data::ActionExecution(a) => {
            let name = a.name.as_ref();
            let category = name.map_or("unknown", |n| n.category.as_str());
            attrs.push(attr("buck2.category", category));
            attrs.push(attr(
                "buck2.identifier",
                name.map_or("", |n| n.identifier.as_str()),
            ));
            if let Some(key) = &a.key {
                if let Some(owner) = &key.owner {
                    use data::action_key::Owner;
                    match owner {
                        Owner::TargetLabel(t)
                        | Owner::TestTargetLabel(t)
                        | Owner::LocalResourceSetup(t) => target_attrs(&mut attrs, t),
                        _ => {}
                    }
                }
            }
            ("action", category.to_owned(), true)
        }
        span_start_event::Data::ExecutorStage(s) => {
            use data::executor_stage_start::Stage;
            let stage = match s.stage {
                Some(Stage::Re(re)) => {
                    use data::re_stage::Stage as Re;
                    match re.stage {
                        Some(Re::Execute(_)) => "execute",
                        Some(Re::Download(_)) => "download",
                        Some(Re::Queue(_)) => "queued",
                        Some(Re::WorkerDownload(_)) => "worker_download",
                        Some(Re::WorkerUpload(_)) => "worker_upload",
                        Some(Re::MaterializeFailedInputs(_)) => "materialize_inputs",
                        Some(Re::QueueOverQuota(_)) => "queue_over_quota",
                        Some(Re::QueueNoWorkerAvailable(_)) => "queue_no_worker_available",
                        Some(Re::QueueAcquiringDependencies(_)) => "queue_acquiring_dependencies",
                        Some(Re::QueueCancelled(_)) => "queue_cancelled",
                        _ => "remote",
                    }
                }
                Some(Stage::Local(_)) => "local",
                Some(Stage::CacheQuery(_)) => "cache_query",
                Some(Stage::CacheHit(_)) => "cache_hit",
                Some(Stage::Prepare(_)) => "prepare",
                None => "unknown",
            };
            ("stage", stage.into(), false)
        }
        span_start_event::Data::MatchDepFiles(_) => ("stage", "match_dep_files".into(), false),
        span_start_event::Data::CacheUpload(_) => ("stage", "cache_upload".into(), false),
        span_start_event::Data::Materialization(_) => ("materialization", "artifact".into(), false),
        span_start_event::Data::FinalMaterialization(_) => {
            ("materialization", "final".into(), false)
        }
        span_start_event::Data::Load(load) => {
            attrs.push(attr("buck2.target", &load.module_id));
            ("phase", "load".into(), false)
        }
        span_start_event::Data::LoadPackage(load) => {
            attrs.push(attr("buck2.target", &load.path));
            ("phase", "load_package".into(), false)
        }
        span_start_event::Data::Analysis(analysis) => {
            attrs.push(attr("buck2.rule", &analysis.rule));
            ("phase", "analysis".into(), false)
        }
        span_start_event::Data::AnalysisStage(_) => ("phase", "analysis_stage".into(), false),
        other => {
            let debug = format!("{other:?}");
            (
                "phase",
                snake(debug.split('(').next().unwrap_or("unknown")),
                false,
            )
        }
    };
    if kind == "phase" {
        attrs.push(attr("buck2.phase", &detail));
    }
    if kind == "stage" {
        attrs.push(attr("buck2.stage", &detail));
    }
    if kind == "materialization" {
        attrs.push(attr("buck2.materialization.kind", &detail));
    }
    (format!("buck2.{kind} {detail}"), attrs, action)
}
fn decode(path: &PathBuf) -> Result<Model, Box<dyn std::error::Error>> {
    decode_with(path, Limits::default())
}
fn decode_with(path: &PathBuf, limits: Limits) -> Result<Model, Box<dyn std::error::Error>> {
    let mut compressed = Vec::new();
    File::open(path)?
        .take(limits.compressed_bytes.saturating_add(1))
        .read_to_end(&mut compressed)?;
    let compressed_over = compressed.len() as u64 > limits.compressed_bytes;
    if compressed_over {
        compressed.truncate(limits.compressed_bytes as usize);
    }
    let (input, frame_reason) = seal_frame(compressed)?;
    let reader = ruzstd::decoding::StreamingDecoder::new(io::Cursor::new(input))
        .map_err(|e| io::Error::new(io::ErrorKind::InvalidData, e.to_string()))?;
    let mut reader = BufReader::with_capacity(
        1 << 20,
        Bounded {
            inner: reader,
            remaining: limits.decompressed_bytes,
        },
    );
    let mut buf = Vec::with_capacity(65536);
    // Without a readable header there is no prefix to export; the error names why.
    match read_record(&mut reader, &mut buf) {
        Ok(Some(())) => {}
        Ok(None) => return Err("empty Buck log".into()),
        Err(e) => return Err(format!("unreadable Buck log header: {e}").into()),
    }
    let _header = data::Invocation::decode(buf.as_slice())
        .map_err(|e| format!("unreadable Buck log header: {e}"))?;
    let mut model = Model {
        uuid: String::new(),
        spans: Vec::new(),
        resource_attrs: Vec::new(),
        critical_ns: None,
        truncated: false,
        stop_reason: None,
        unknown_fields: 0,
    };
    let mut by_id = HashMap::new();
    let mut critical = HashSet::new();
    let mut last_time = 0;
    let mut records = 1u64;
    let mut critical_ids_read = 0u64;
    loop {
        match read_record(&mut reader, &mut buf) {
            Ok(Some(())) => {}
            Ok(None) => break,
            Err(e) if e.kind() == io::ErrorKind::UnexpectedEof => {
                model.truncated = true;
                break;
            }
            Err(e) if e.kind() == io::ErrorKind::FileTooLarge => {
                model.stop_reason = Some(format!(
                    "limit: decompressed bytes exceed {}",
                    limits.decompressed_bytes
                ));
                break;
            }
            Err(e) => {
                model.stop_reason = Some(format!("corrupt: {e}"));
                break;
            }
        }
        records += 1;
        if records > limits.records {
            model.stop_reason = Some(format!("limit: records exceed {}", limits.records));
            break;
        }
        let progress = match CommandProgress::decode(buf.as_slice()) {
            Ok(progress) => progress,
            Err(e) => {
                model.stop_reason = Some(format!("corrupt: record {records}: {e}"));
                break;
            }
        };
        // Prost drops fields outside the pinned schema. Record each envelope
        // with discarded bytes; ingestion remains forward-compatible.
        model.unknown_fields += usize::from(progress.encoded_len() < buf.len());
        let Some(command_progress::Progress::Event(e)) = progress.progress else {
            continue;
        };
        if model.uuid.is_empty() {
            model.uuid = e.trace_id.clone();
        }
        let now = timestamp(e.timestamp.as_ref());
        last_time = last_time.max(now);
        match e.data {
            Some(buck_event::Data::SpanStart(start)) => {
                if model.spans.len() >= limits.spans {
                    model.stop_reason = Some(format!("limit: spans exceed {}", limits.spans));
                    break;
                }
                if let Some(data) = start.data {
                    if let span_start_event::Data::Command(command) = &data {
                        for (source, target) in [
                            ("buck2_revision", "service.version"),
                            ("hostname", "host.name"),
                            ("os", "os.type"),
                            ("arch", "host.arch"),
                            ("materializer", "buck2.materializer"),
                        ] {
                            if let Some(value) = command.metadata.get(source) {
                                model.resource_attrs.push(attr(target, value));
                            }
                        }
                    }
                    let (name, mut attrs, action) = start_shape(data);
                    attrs.push(int_attr("buck2.span_id", e.span_id));
                    let label = if action {
                        let target = attrs
                            .iter()
                            .find(|a| a["key"] == "buck2.target")
                            .and_then(|a| a["value"]["stringValue"].as_str())
                            .and_then(|target| target.rsplit('/').next())
                            .unwrap_or("");
                        let identifier = attrs
                            .iter()
                            .find(|a| a["key"] == "buck2.identifier")
                            .and_then(|a| a["value"]["stringValue"].as_str())
                            .unwrap_or("");
                        format!(
                            "{} {}",
                            name.strip_prefix("buck2.action ").unwrap_or("action"),
                            if target.is_empty() {
                                identifier
                            } else {
                                target
                            }
                        )
                    } else {
                        name.clone()
                    };
                    attrs.push(attr(
                        "span.label",
                        label.chars().take(39).collect::<String>(),
                    ));
                    by_id.insert(e.span_id, model.spans.len());
                    model.spans.push(Span {
                        id: e.span_id,
                        parent: e.parent_id,
                        start: now,
                        end: 0,
                        name,
                        attrs,
                        critical: false,
                        action,
                        cache_hit: false,
                        execution_ns: None,
                        queue_ns: None,
                        ended: false,
                    });
                }
            }
            Some(buck_event::Data::SpanEnd(end)) => {
                if let Some(&index) = by_id.get(&e.span_id) {
                    let span = &mut model.spans[index];
                    // Only the first end counts; repeats must not grow attributes.
                    if span.ended {
                        continue;
                    }
                    span.ended = true;
                    span.end = now;
                    if let Some(data) = end.data {
                        match data {
                            span_end_event::Data::ActionExecution(a) => {
                                let kind = action_kind(a.execution_kind);
                                span.cache_hit = matches!(
                                    kind,
                                    "action_cache" | "remote_dep_file_cache" | "local_action_cache"
                                );
                                span.attrs.push(attr("buck2.execution_kind", kind));
                                span.attrs
                                    .push(bool_attr("buck2.cache_hit", span.cache_hit));
                                span.attrs.push(bool_attr("buck2.failed", a.failed));
                                span.execution_ns = a
                                    .commands
                                    .iter()
                                    .rev()
                                    .find_map(|command| {
                                        command
                                            .details
                                            .as_ref()
                                            .and_then(|details| details.metadata.as_ref())
                                            .and_then(|metadata| metadata.execution_time.as_ref())
                                            .map(duration_ns)
                                    })
                                    .or_else(|| a.wall_time.as_ref().map(duration_ns));
                                let mut queue = None;
                                for command in &a.commands {
                                    let measured = command.details.as_ref().and_then(|details| {
                                        details.metadata.as_ref()
                                            .and_then(|metadata| metadata.queue_duration.as_ref())
                                            .or_else(|| details.command_kind.as_ref()
                                                .and_then(|kind| kind.command.as_ref())
                                                .and_then(|kind| match kind {
                                                    data::command_execution_kind::Command::RemoteCommand(remote) =>
                                                        remote.queue_time.as_ref(),
                                                    _ => None,
                                                }))
                                            .map(duration_ns)
                                    });
                                    if let Some(ns) = measured {
                                        queue = Some(queue.unwrap_or(0u64).saturating_add(ns));
                                    }
                                }
                                span.queue_ns = queue;
                                span.attrs
                                    .push(int_attr("buck2.output_size", a.output_size));
                                if let Some(bytes) = a.input_files_bytes {
                                    span.attrs.push(int_attr("buck2.input_files_bytes", bytes));
                                }
                            }
                            span_end_event::Data::Materialization(m) => {
                                span.attrs.push(int_attr("buck2.file_count", m.file_count));
                                span.attrs
                                    .push(int_attr("buck2.total_bytes", m.total_bytes));
                                span.attrs.push(attr("buck2.path", m.path));
                            }
                            span_end_event::Data::Command(c) => {
                                span.attrs.push(bool_attr("buck2.is_success", c.is_success))
                            }
                            _ => {}
                        }
                    }
                }
            }
            Some(buck_event::Data::Instant(instant)) => {
                if let Some(instant_event::Data::BuildGraphInfo(info)) = instant.data {
                    // Buck emits the graph after the spans it names; ids of unknown
                    // spans cannot mark anything and are not retained.
                    let mut total = None;
                    for entry in &info.critical_path2 {
                        if let Some(ns) = entry.duration.as_ref().map(duration_ns) {
                            total = Some(total.unwrap_or(0u64).saturating_add(ns));
                        }
                    }
                    model.critical_ns = total;
                    for id in info.critical_path2.into_iter().flat_map(|e| e.span_ids) {
                        critical_ids_read += 1;
                        if critical_ids_read > limits.critical_ids {
                            break;
                        }
                        if by_id.contains_key(&id) {
                            critical.insert(id);
                        }
                    }
                    if critical_ids_read > limits.critical_ids {
                        model.stop_reason = Some(format!(
                            "limit: critical path ids exceed {}",
                            limits.critical_ids
                        ));
                        break;
                    }
                }
            }
            _ => {}
        }
    }
    // Framing damage explains any record-level stop; it wins over the symptom.
    if compressed_over {
        model.stop_reason = Some(format!(
            "limit: compressed bytes exceed {}",
            limits.compressed_bytes
        ));
    } else if let Some(reason) = frame_reason {
        if reason.starts_with("truncated") {
            model.truncated = true;
        } else if model.stop_reason.is_none() || reason.starts_with("corrupt") {
            model.stop_reason = Some(reason);
        }
    }
    if model.uuid.is_empty() {
        return Err("no Buck event in log".into());
    }
    for span in &mut model.spans {
        if !span.ended {
            span.end = last_time.max(span.start);
            span.attrs.push(bool_attr("buck2.unclosed", true));
        }
        span.critical = critical.contains(&span.id);
        if span.action {
            span.attrs
                .push(bool_attr("buck2.critical_path", span.critical));
        }
    }
    let actions = model.spans.iter().filter(|s| s.action).count();
    let hits = model
        .spans
        .iter()
        .filter(|s| s.action && s.cache_hit)
        .count();
    let critical_actions = model
        .spans
        .iter()
        .filter(|s| s.action && s.critical)
        .count();
    let mut intervals: Vec<_> = model
        .spans
        .iter()
        .filter(|s| s.action)
        .map(|s| (s.start, s.end))
        .collect();
    intervals.sort_unstable();
    if let Some(command) = model
        .spans
        .iter_mut()
        .find(|s| s.name.starts_with("buck2.command "))
    {
        command.attrs.extend([
            int_attr("buck2.action_count", actions),
            int_attr("buck2.cache_hit_count", hits),
            int_attr("buck2.critical_path_action_count", critical_actions),
        ]);
        // A per-log silence estimate; a later cross-command join assigns causal owners.
        let (mut previous_end, mut gaps, mut total_ns, mut max_ns) = (command.start, 0, 0u64, 0u64);
        for (start, end) in intervals {
            let gap = start.saturating_sub(previous_end);
            if gap >= 1_000_000_000 {
                gaps += 1;
                total_ns += gap;
                max_ns = max_ns.max(gap);
            }
            previous_end = previous_end.max(end);
        }
        command.attrs.extend([
            int_attr("buck2.daemon_wait.gap_count", gaps),
            int_attr("buck2.daemon_wait.total_ms", total_ns / 1_000_000),
            int_attr("buck2.daemon_wait.max_ms", max_ns / 1_000_000),
        ]);
    }
    Ok(model)
}
fn make_views(
    model: &Model,
    parent: Option<&(String, String)>,
) -> Vec<(&'static str, String, Vec<Value>)> {
    let full_trace = hash_hex(&format!("{}:full", model.uuid), 32);
    let critical_trace = parent.map_or_else(
        || hash_hex(&format!("{}:critical", model.uuid), 32),
        |p| p.0.clone(),
    );
    let command_id = model
        .spans
        .iter()
        .find(|s| s.name.starts_with("buck2.command "))
        .map_or(0, |s| s.id);
    let parents: HashMap<u64, u64> = model.spans.iter().map(|s| (s.id, s.parent)).collect();
    let critical_ids: HashSet<u64> = model
        .spans
        .iter()
        .filter(|s| s.critical)
        .map(|s| s.id)
        .collect();
    let mandatory: HashSet<u64> = model
        .spans
        .iter()
        .filter(|s| {
            s.critical
                || s.name.starts_with("buck2.command ")
                || (s.name.starts_with("buck2.stage ") && critical_ids.contains(&s.parent))
        })
        .map(|s| s.id)
        .collect();
    let select = |threshold: u64| {
        let mut kept: HashSet<u64> = model
            .spans
            .iter()
            .filter(|s| mandatory.contains(&s.id) || s.end.saturating_sub(s.start) >= threshold)
            .map(|s| s.id)
            .collect();
        for s in &model.spans {
            if kept.contains(&s.id) {
                let mut p = s.parent;
                while let Some(&parent_id) = parents.get(&p) {
                    if !kept.insert(p) {
                        break;
                    }
                    p = parent_id;
                }
            }
        }
        kept
    };
    let mut threshold = 1_000_000_000;
    let mut selected = select(threshold);
    if selected.len() > 1200 {
        let max_duration = model
            .spans
            .iter()
            .map(|s| s.end.saturating_sub(s.start))
            .max()
            .unwrap_or(0);
        let (mut lo, mut hi) = (threshold, max_duration.saturating_add(1));
        while lo < hi {
            let mid = lo + (hi - lo) / 2;
            if select(mid).len() <= 1200 {
                hi = mid;
            } else {
                lo = mid + 1;
            }
        }
        threshold = lo;
        selected = select(threshold);
    }
    // Spans whose parent is absent from the log hang off the command span.
    let effective_parent = |s: &Span| {
        if parents.contains_key(&s.parent) {
            s.parent
        } else {
            command_id
        }
    };
    let mut dropped_children: HashMap<u64, usize> = HashMap::new();
    for s in model.spans.iter().filter(|s| s.id != command_id) {
        if !selected.contains(&s.id) {
            *dropped_children.entry(effective_parent(s)).or_default() += 1;
        }
    }
    // Mandatory spans (critical path, its stages, ancestors) are never dropped
    // to meet the cap; an overflow is stamped instead of hidden.
    let cap_exceeded = selected.len() > 1200;
    let render = |trace: &str, view: &str, subset: Option<&HashSet<u64>>| {
        model
            .spans
            .iter()
            .filter(|s| subset.is_none_or(|set| set.contains(&s.id)))
            .map(|s| {
                let root = s.id == command_id;
                let parent_id = if root {
                    parent.map(|p| p.1.clone()).filter(|_| view == "critical")
                } else {
                    Some(span_id(&model.uuid, effective_parent(s)))
                };
                let mut attributes = s.attrs.clone();
                let mut links = Vec::new();
                if root {
                    attributes.push(attr("buck2.trace.view", view));
                    if model.truncated {
                        attributes.push(bool_attr("buck2.ingest.truncated", true));
                    }
                    if let Some(reason) = &model.stop_reason {
                        attributes.push(attr("buck2.ingest.stop_reason", reason));
                    }
                    if view == "critical" {
                        attributes.push(attr("buck2.trace.full_id", &full_trace));
                        attributes.push(int_attr("buck2.critical_threshold_ns", threshold));
                        if cap_exceeded {
                            attributes.push(bool_attr("buck2.critical_cap_exceeded", true));
                            attributes.push(int_attr("buck2.critical_span_count", selected.len()));
                        }
                        links.push(json!({"traceId":full_trace,"spanId":span_id(&model.uuid, command_id)}));
                    } else if let Some((caller_trace, caller_span)) = parent {
                        // The separate full trace points back at the caller command span.
                        links.push(json!({"traceId":caller_trace,"spanId":caller_span}));
                    }
                }
                if view == "critical" {
                    if let Some(&dropped) = dropped_children.get(&s.id) {
                        attributes.push(int_attr("buck2.dropped_children", dropped));
                    }
                }
                let mut span = json!({"traceId":trace,"spanId":span_id(&model.uuid,s.id),"name":s.name,"kind":1,"startTimeUnixNano":s.start.to_string(),"endTimeUnixNano":s.end.to_string(),"attributes":attributes,"links":links});
                if let Some(parent_id) = parent_id {
                    span["parentSpanId"] = json!(parent_id);
                }
                span
            })
            .collect::<Vec<Value>>()
    };
    vec![
        (
            "critical",
            critical_trace.clone(),
            render(&critical_trace, "critical", Some(&selected)),
        ),
        (
            "full",
            full_trace.clone(),
            render(&full_trace, "full", None),
        ),
    ]
}
fn chunks(spans: &[Value], resource: &Value) -> Result<Vec<Vec<u8>>, Box<dyn std::error::Error>> {
    let mut result = Vec::new();
    let mut group = Vec::new();
    let empty_size = payload(resource, &[]).len();
    let mut size = empty_size;
    for span in spans {
        let bytes = serde_json::to_vec(span)?.len();
        if size + bytes + usize::from(!group.is_empty()) > MAX_OTLP_BODY {
            if group.is_empty() {
                return Err("single OTLP span exceeds collector body limit".into());
            }
            result.push(payload(resource, &group));
            group.clear();
            size = empty_size;
        }
        if size + bytes > MAX_OTLP_BODY {
            return Err("single OTLP span exceeds collector body limit".into());
        }
        size += bytes + usize::from(!group.is_empty());
        group.push(span);
    }
    if !group.is_empty() {
        result.push(payload(resource, &group));
    }
    Ok(result)
}
fn payload(resource: &Value, spans: &[&Value]) -> Vec<u8> {
    serde_json::to_vec(&json!({"resourceSpans":[{"resource":resource,"scopeSpans":[{"scope":{"name":"buck2-events"},"spans":spans}]}]})).expect("OTLP JSON")
}

const HISTOGRAM_BOUNDS: [f64; 7] = [0.001, 0.01, 0.1, 1.0, 10.0, 60.0, 600.0];

#[derive(Default)]
struct Histogram {
    count: u64,
    sum: f64,
    buckets: [u64; 8],
}

impl Histogram {
    fn observe(&mut self, duration_ns: u64) {
        let seconds = duration_ns as f64 / 1_000_000_000.0;
        let bucket = HISTOGRAM_BOUNDS
            .iter()
            .position(|bound| seconds <= *bound)
            .unwrap_or(HISTOGRAM_BOUNDS.len());
        self.count += 1;
        self.sum += seconds;
        self.buckets[bucket] += 1;
    }
}

fn metric_category(value: &str) -> &'static str {
    match value {
        "compile" => "compile",
        "link" => "link",
        "test" => "test",
        "write" => "write",
        "copy" => "copy",
        _ => "other",
    }
}

fn metric_subcommand(value: &str) -> &'static str {
    match value {
        "build" => "build",
        "test" => "test",
        "run" => "run",
        "query" => "query",
        "uquery" => "uquery",
        "cquery" => "cquery",
        "audit" => "audit",
        "targets" => "targets",
        "install" => "install",
        _ => "other",
    }
}

fn metric_point(hist: &Histogram, attributes: Vec<Value>, start: u64, end: u64) -> Value {
    json!({
        "attributes": attributes,
        "startTimeUnixNano": start.to_string(),
        "timeUnixNano": end.to_string(),
        "count": hist.count.to_string(),
        "sum": hist.sum,
        "bucketCounts": hist.buckets.map(|count| count.to_string()),
        "explicitBounds": HISTOGRAM_BOUNDS,
    })
}

fn metric_histogram(name: &str, points: Vec<Value>) -> Value {
    json!({"name":name,"unit":"s","histogram":{"aggregationTemporality":1,"dataPoints":points}})
}

fn metric_payload(model: &Model) -> Vec<u8> {
    let command = model
        .spans
        .iter()
        .find(|span| span.name.starts_with("buck2.command "));
    let (start, end) = command.map_or((0, 0), |span| (span.start, span.end));
    let subcommand = metric_subcommand(
        command
            .and_then(|span| span.name.strip_prefix("buck2.command "))
            .unwrap_or(""),
    );
    let command_points = command.map_or_else(Vec::new, |span| {
        let mut hist = Histogram::default();
        hist.observe(span.end.saturating_sub(span.start));
        vec![metric_point(
            &hist,
            vec![attr("subcommand", subcommand)],
            start,
            end,
        )]
    });
    let critical_points = model.critical_ns.map_or_else(Vec::new, |ns| {
        let mut hist = Histogram::default();
        hist.observe(ns);
        vec![metric_point(
            &hist,
            vec![attr("subcommand", subcommand)],
            start,
            end,
        )]
    });
    let mut counts = BTreeMap::<(&str, &str, bool), u64>::new();
    let mut execution = BTreeMap::<&str, Histogram>::new();
    let mut queue = BTreeMap::<&str, Histogram>::new();
    for span in model.spans.iter().filter(|span| span.action) {
        let category = metric_category(span.name.strip_prefix("buck2.action ").unwrap_or(""));
        let kind = span
            .attrs
            .iter()
            .find(|value| value["key"] == "buck2.execution_kind")
            .and_then(|value| value["value"]["stringValue"].as_str())
            .unwrap_or("not_set");
        *counts.entry((category, kind, span.cache_hit)).or_default() += 1;
        if let Some(ns) = span.execution_ns {
            execution.entry(category).or_default().observe(ns);
        }
        if let Some(ns) = span.queue_ns {
            queue.entry(category).or_default().observe(ns);
        }
    }
    let action_points: Vec<_> = counts
        .into_iter()
        .map(|((category, kind, cache_hit), count)| {
            json!({"attributes":[attr("category",category),attr("execution_kind",kind),
            bool_attr("cache_hit",cache_hit)],
            "startTimeUnixNano":start.to_string(),"timeUnixNano":end.to_string(),
            "asInt":count.to_string()})
        })
        .collect();
    let duration_points = |aggregates: BTreeMap<&str, Histogram>| {
        aggregates
            .into_iter()
            .map(|(category, hist)| {
                metric_point(&hist, vec![attr("category", category)], start, end)
            })
            .collect()
    };
    let metrics = vec![
        metric_histogram("buck2.command.duration", command_points),
        metric_histogram("buck2.critical_path.duration", critical_points),
        json!({"name":"buck2.action.count","sum":{"aggregationTemporality":1,
            "isMonotonic":true,"dataPoints":action_points}}),
        metric_histogram(
            "buck2.action.execution.duration",
            duration_points(execution),
        ),
        metric_histogram("buck2.action.queue.duration", duration_points(queue)),
    ];
    serde_json::to_vec(&json!({"resourceMetrics":[{
        "resource":{"attributes":[attr("service.name","effect-utils-buck2")]},
        "scopeMetrics":[{"scope":{"name":"buck2-events"},"metrics":metrics}]
    }]}))
    .expect("OTLP metrics JSON")
}

#[cfg(test)]
mod tests;
