/**
 * .envrc.local Generator
 *
 * Generates environment variable configuration for direnv integration.
 * Output: .envrc.local in the megarepo root.
 */

import { FileSystem, Path } from '@effect/platform'
import { Effect } from 'effect'
import { type MegarepoConfig } from '../config.ts'

export interface EnvrcGeneratorOptions {
  /** Path to the megarepo root */
  readonly megarepoRoot: string
  /** The megarepo config */
  readonly config: typeof MegarepoConfig.Type
}

/**
 * Generate .envrc.local content
 */
export const generateEnvrcContent = (options: EnvrcGeneratorOptions): string => {
  const memberNames = Object.keys(options.config.members).join(',')

  return `# Generated by megarepo - do not edit manually
# Regenerate with: mr generate

export MEGAREPO_ROOT="${options.megarepoRoot}"
export MEGAREPO_MEMBERS="${memberNames}"
`
}

/**
 * Generate .envrc.local file
 */
export const generateEnvrc = (options: EnvrcGeneratorOptions) =>
  Effect.gen(function* () {
    const fs = yield* FileSystem.FileSystem
    const pathService = yield* Path.Path

    const content = generateEnvrcContent(options)
    const outputPath = pathService.join(options.megarepoRoot, '.envrc.local')

    yield* fs.writeFileString(outputPath, content)

    return { path: outputPath, content }
  })
