[package]
name = "buck2-portable-toolchain"
workspace = "../.."
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
default-run = "buck2-portable-toolchain"

[lib]
name = "buck2_portable_toolchain"
path = "src/lib.rs"

[[bin]]
name = "buck2-portable-toolchain"
path = "src/main.rs"

[dependencies]
buck2-tool-core = { path = "../core" }
clap = { version = "4", features = ["derive"] }
serde_json.workspace = true
tar = { version = "0.4", default-features = false }

[dev-dependencies]
tempfile.workspace = true
