[package]
name = "effect-rust-fixture-wasm"
workspace = "../.."
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "effect_rust_fixture_wasm"
crate-type = ["cdylib", "rlib"]

[features]
default = ["wasm"]
wasm = []

[dependencies]
hash-interop = { path = "../hash-interop" }
math-interop = { path = "../math-interop" }
